'use client';

import React, { createContext, useContext, useState, useEffect } from 'react';

export type Locale = 'ka' | 'en' | 'ru';

type Translations = Record<string, string>;

const translations: Record<Locale, Translations> = {
  ka: {
    // Navbar / Header
    logo_text: 'ARTRON',
    logo_sub: 'სპორტული SaaS & IoT',
    lang_selector: 'ენა',
    nav_ecosystem: 'ეკოსისტემა',
    nav_roi: 'ROI კალკულატორი',
    nav_partners: 'პარტნიორები',
    nav_booking: 'დემო ჯავშანი',
    nav_faq: 'FAQ',

    // Hero Section
    hero_badge: 'DUAL-CORE SHOWCASE • B2B + B2C ინტეგრაცია',
    hero_title_1: 'ფიტნესისა და სპორტის',
    hero_title_gradient: 'ავტომატიზაციის ეკოსისტემა',
    hero_subtitle: 'სპორტული ცენტრებისა და აუზების მართვის უახლესი პლატფორმა: გააერთიანეთ B2B CRM პანელი და B2C მობილური აპლიკაცია. გაათავისუფლეთ რეცეფცია რუტინისგან 24/7-ზე ავტომატიზებული IoT ტურნიკეტებით, უშეცდომოდ დააკმაყოფილეთ კანონის მოთხოვნები სამუშაო დროის ავტომატური აღრიცხვით (ბრძანება №01-15/ნ) და გაზარდეთ გაყიდვები წვდომების, აბონემენტებისა და პერსონალური ვარჯიშების ონლაინ მარკეტპლეისით.',
    cta_b2b: 'მოითხოვეთ B2B დემო',
    cta_b2c: 'მობილური აპლიკაცია',

    // Hero Stats
    stat_admin_title: '30% ნაკლები დრო',
    stat_admin_desc: 'ადმინისტრაციულ მუშაობაზე',
    stat_access_title: '24/7 ავტომატიზაცია',
    stat_access_desc: 'IoT ტურნიკეტების მართვა',
    stat_bookings_title: '0% დაკარგული ჯავშანი',
    stat_bookings_desc: 'AI კამპანიების წყალობით',

    // Dashboard Preview (B2B)
    db_title: 'ARTRON მართვის პანელი',
    db_status: 'IoT კონტროლერი კავშირშია',
    db_kpi_members: 'აქტიური წევრები',
    db_kpi_entries: 'დღიური შესვლა',
    db_kpi_winback: 'დაბრუნების კოეფიციენტი',
    db_logs_title: 'ტურნიკეტის ცოცხალი ლოგი',
    db_log_in: 'შემოვიდა',
    db_log_out: 'გავიდა',
    db_user: 'მომხმარებელი',
    db_employee_time: 'სამუშაო დრო (№01-15/ნ)',
    db_toggle_live: 'ცოცხალი ტელემეტრია',
    db_toggle_screenshot: 'პლატფორმის ინტერფეისი',
    db_screenshot_alt: 'მართვის პანელის ინტერფეისის სკრინშოტი',
    db_screenshot_zoom: 'დააჭირეთ სურათს გასადიდებლად',

    // Business Stats Showcase Section
    stats_sec_title: 'მართვის პანელის ანალიტიკა: რეალური ბიზნეს მეტრიკები',
    stats_sec_subtitle: 'ართრონი აგროვებს და აანალიზებს ათასობით ოპერაციულ სიგნალს, რათა დაგეხმაროთ დარბაზის ფინანსური და ორგანიზაციული ეფექტურობის გაზრდაში.',
    stats_card_ltv_title: 'კლიენტთა შენარჩუნება (LTV & Win-Back)',
    stats_card_ltv_metric: '+22%',
    stats_card_ltv_sub: 'დაბრუნებული წევრები',
    stats_card_ltv_feat1: 'მყისიერი Cron-კამპანიები',
    stats_card_ltv_feat2: 'შემცირებული ჩურნ-რეიტი',
    stats_card_ltv_feat3: 'აღდგენილი ყოველთვიური შემოსავალი',
    stats_card_iot_title: 'IoT წვდომის ავტომატიზაცია',
    stats_card_iot_metric: '-45სთ',
    stats_card_iot_sub: 'ადმინისტრაციული დრო კვირაში',
    stats_card_iot_feat1: '100% ავტონომიური ტურნიკეტები',
    stats_card_iot_feat2: 'ნულოვანი დამოკიდებულება რეცეფციაზე',
    stats_card_iot_feat3: 'უსაფრთხო Anti-Passback კონტროლი',
    stats_card_labor_title: 'შრომის უსაფრთხოება (№01-15/ნ)',
    stats_card_labor_metric: '100%',
    stats_card_labor_sub: 'აუდიტის დაცულობა',
    stats_card_labor_feat1: 'ავტომატური შესვლა/გასვლის ტაბელები',
    stats_card_labor_feat2: 'შრომის ინსპექციასთან შესაბამისობა',
    stats_card_labor_feat3: 'აცილებული საჯარიმო სანქციები',
    stats_card_trainers_title: 'მწვრთნელების გაყიდვები',
    stats_card_trainers_metric: '+35%',
    stats_card_trainers_sub: 'პაკეტების გაყიდვების ზრდა',
    stats_card_trainers_feat1: 'აპლიკაციის ონლაინ მარკეტპლეისი',
    stats_card_trainers_feat2: 'ნულოვანი კალენდარული კონფლიქტი',
    stats_card_trainers_feat3: 'ავტომატიზირებული საკომისიოები',

    // Mobile Preview (B2C)
    mobile_title: 'ARTRON მობილური აპლიკაცია',
    mobile_welcome: 'გამარჯობა, სპორტსმენო!',
    mobile_qr_pass: 'დინამიური QR საშვი',
    mobile_qr_desc: 'დაასკანირეთ ტურნიკეტზე შესასვლელად',
    mobile_sub_status: 'ჩემი აბონემენტი',
    mobile_sub_active: 'აქტიური • 14 დღე დარჩა',
    mobile_progress: 'ჩემი აქტივობა',
    mobile_workouts: 'ჩატარებული ვარჯიში',
    mobile_nfc_desc: 'NFC წვდომა აქტიურია',

    // Cookie Banner
    cookie_title: 'ქუქი-ფაილების და კონფიდენციალურობის მართვა',
    cookie_desc: 'შპს „ართრონი“ (ს/კ 412799431, ქუთაისი, ნიკეას ქ., N 46ა, ბ. 17, info@artron.ge) იყენებს ქუქი-ფაილებს საიტის მუშაობის გაუმჯობესების, ანალიტიკისა და მარკეტინგის მიზნებისთვის, Google Consent Mode v2 სტანდარტების დაცვით.',
    cookie_accept_all: 'ყველას მიღება',
    cookie_decline_all: 'ყველაზე უარი',
    cookie_settings: 'პარამეტრები',
    cookie_save: 'არჩევანის შენახვა',
    cookie_necessary_title: 'აუცილებელი',
    cookie_necessary_desc: 'საიტის მუშაობისთვის სავალდებულო მონაცემები (ენა, სესია, უსაფრთხоება). არ ითხოვს წინასწარ თანხმობას.',
    cookie_analytics_title: 'ანალიტიკა',
    cookie_analytics_desc: 'გვეხმარется გავაანალიზოთ საიტის ტრაფიკი და მომხმარებლის ქცევა (Google Analytics).',
    cookie_marketing_title: 'მარკეტინგი',
    cookie_marketing_desc: 'გამოიყენება პერსონალიზებული რეკლამებისა და Google Ads-ის მიზნებისთვის.',
    cookie_policy_link: 'იხილეთ კონფიდენციალურობის პოლიტიკა',

    // Services Section
    services_section_title: 'სერვისების ეკოსისტემა',
    services_section_subtitle: 'ართრონის ორმაგი ძალა — ერთიანი პლატფორმა ადმინისტრატორებისა და სპორტსმენებისთვის',
    services_tab_b2b: 'B2B ბიზნეს ინფრასტრუქტურა',
    services_tab_b2c: 'B2C მობილური აპლიკაცია',
    service_iot_title: 'IoT აპარატურული ინტეგრაცია',
    service_iot_desc: 'ჭკვიანი ტურნიკეტების, ბიომეტრიული და NFC მკითხველების პირდაპირი TCP/Socket კავშირი. 24/7 ავტომატური წვდომა პერსონალის გარეშე.',
    service_worktime_title: 'სამუშაო დროის აღრიცხვა (ბრძანება №01-15/ნ)',
    service_worktime_desc: 'შრომის ინსპექციის მოთხოვნებთან სრული შესაბამისობა. ბიომეტრიული შესვლა/გასვლა, ავტომატური ტაბელები და სამუშაო საათების ექსპორტი.',
    service_worktime_short: 'სამუშაო დრო (№01-15/ნ)',
    service_federation_title: 'ფედერაციების მართვა',
    service_federation_desc: 'ლიცენზირების, სპორტსმენთა რეესტრებისა და ტურნირების ცენტრალიზებული მართვა. ინტეგრირებული B2B და B2C მოდულები.',
    service_marketplace_title: 'აბონემენტების მარკეტპლეისი',
    service_marketplace_desc: 'აბონემენტების, პერსონალური ვარჯიშებისა და აქსესუარების ონლაინ გაყიდვები. 14-დღიანი კანონისმიერი დაბრუნების გარანტიით.',
    service_passbook_title: 'მობილური საშვი & QR Pass',
    service_passbook_desc: 'შესვლა დარბაზში დინამიური, დაცული QR კოდით ან NFC ჩიპით. გამორიცხავს ბარათების დაკარგვას და არალეგალურ გადაცემას.',
    service_metrics_title: 'სპორტული მეტრიკები და პროგრესი',
    service_metrics_desc: 'ვიზიტების კალენდარი, ვარჯიშის ისტორია, აქტივობის მონიტორინგი და მწვრთნელების რეიტინგები რეალურ დროში.',

    // ROI Calculator
    roi_title: 'ROI კალკულატორი დარბაზებისთვის',
    roi_subtitle: 'გამოთვალეთ ართრონის დანერგვით მიღებული პირდაპირი ფინანსური და საოპერაციო სარგებელი',
    roi_members_label: 'აქტიური წევრების რაოდენობა',
    roi_staff_label: 'თანამშრომლები და მწვრთნელები',
    roi_time_saved_title: 'დაზოგილი დრო',
    roi_time_saved_desc: 'საათი თვეში ადმინისტრაციულ და წვდომის კონტროლზე',
    roi_revenue_title: 'დამატებითი შემოსავალი',
    roi_revenue_desc: 'წლიური ზრდა ონლაინ გაყიდვებითა და შენარჩუნებით',
    roi_overhead_title: 'ადმინისტრაციული ეკონომია',
    roi_overhead_desc: 'საოპერაციო ხარჯების შემცირება ავტომატიზაციით',
    roi_cta: 'მოითხოვეთ უფასო დემო პრეზენტაცია',

    // FAQ Section
    faq_title: 'ხშირად დასმული კითხვები',
    faq_subtitle: 'მიიღეთ პასუხები ართრონის პლატფორმის, IoT აპარატურისა და იურიდიული საკითხების შესახებ',
    faq_tab_all: 'ყველა კითხვა',
    faq_tab_b2b: 'B2B ბიზნესისთვის',
    faq_tab_b2c: 'B2C სპორტსმენებისთვის',
    faq_q1: 'რამდენ ხანში მონტაჟდება IoT ტურნიკეტი?',
    faq_a1: 'ფიზიკური ინსტალაცია და ქსელური კონფიგურაცია ჩვეულებრივ სრულდება 1-3 სამუშაო დღეში. ჩვენი გუნდი უზრუნველყოფს სრულ ტექნიკურ მხარდაჭერასა და კავშირს ARTRON SaaS პლატფორმასთან.',
    faq_q2: 'როგორ არის დაცული მონაცემთა უსაფრთხოება და იზოლაცია (Multi-Tenancy)?',
    faq_a2: 'თითოეული კლიენტის (Tenant) მონაცემები მკაცრად იზოლირებულია ლოგიკურ და მონაცემთა ბაზის დონეზე. სენსიტიური პერსონალური მონაცემები (მაგ. პირადი ნომერი) იშიფრება AES-256-GCM ალგორითმით.',
    faq_q3: 'შეესაბამება თუ არა სამუშაო დროის აღრიცხვა საქართველოს კანონმდებლობას (ბრძანება №01-15/ნ)?',
    faq_a3: 'დიახ, ართრონის სამუშაო დროის აღრიცხვის მოდული სრულად შეესაბამება საქართველოს ოკუპირებული ტერიტორიებიდან დევნილთა, შრომის, ჯანმრთელობისა და სოციალური დაცვის მინისტრის ბრძანება №01-15/ნ მოთხოვნებს. სისტემა ავტომატურად აგენერირებს ელექტრონულ ტაბელებს შრომის ინსპექციისთვის.',
    faq_q4: 'რა ხდება ხელშეკრულების შეწყვეტისას? როგორ ხდება მონაცემთა ექსპორტი (30-დღიანი წესი)?',
    faq_a4: 'ხელშეკრულების შეწყვეტის შემდეგ, საოპერაციო მონაცემები ინახება 30 დღის განმავლობაში, რათა შეძლოთ მათი სრული ექსპორტი. ამ ვადის გასვლისთანავე მონაცემები იშლება, გარდა ფინანსური ტრანზაქციებისა, რომლებიც საგადასახადო კოდექსის შესაბამისად ინახება 3 წლის განმავლობაში.',
    faq_q5: 'ვრცელდება თუ არა 14-დღიანი თანხის დაბრუნების გარანტია მობილური აპლიკაციის აბონემენტებზე?',
    faq_a5: 'დიახ, საქართველოს კანონის \'მომხმარებლის უფლებების დაცვის შესახებ\' შესაბამისად, მობილური აპლიკაციით შეძენილ აბონემენტებზე მოქმედებს 14-დღიანი უპირობო დაბრუნების წესი, თუ მომსახურებით სარგებლობა არ დაწყებულა.',
    faq_q6: 'რამდენად უსაფრთხოა მობილური QR საშვი? შესაძლებელია თუ არა მისი სხვისთვის გადაცემა?',
    faq_a6: 'ARTRON-ის მობილური QR საშვი არის დინამიური და ავტომატურად ახლდება ყოველ 15 წამში. მისი სკრინშოტის გაზიარება შეუძლებელია, რაც სრულად გამორიცხავს საშვის არალეგალურ გადაცემას მესამე პირებისთვის.',
    faq_q7: 'მუშაობს თუ არა ტურნიკეტი ინტერნეტის გათიშვისას (Offline რეჟიმი)?',
    faq_a7: 'დიახ, ტურნიკეტის კონტროლერები ინახავენ აქტიური საშვების ადგილობრივ ქეშს. ინტერნეტის გათიშვის შემთხვევაშიც კი, ავტორიზებული წევრებისა და თანამშრომლების შესვლა შეუფერხებლად გაგრძელდება, ხოლო მონაცემები სინქრონიზდება კავშირის აღდგენისთანავე.',

    // AI Bot Widget
    ai_widget_launcher: 'დასვით კითხვა AI ასისტენტს',
    ai_widget_title: 'ARTRON AI ასისტენტი',
    ai_widget_subtitle: 'ონლაინ • გიპასუხებთ მომენტალურად',
    ai_widget_placeholder: 'ჩაწერეთ თქვენი შეკითხვა...',
    ai_widget_welcome: 'გამარჯობა! მე ვარ ართრონის ინტელექტუალური ასისტენტი. რით შემიძლია დაგეხმაროთ?',
    ai_widget_quick_1: 'ტურნიკეტის მონტაჟი',
    ai_widget_quick_2: 'სამუშაო დრო (№01-15/ნ)',
    ai_widget_quick_3: 'თანხის დაბრუნება',
    ai_widget_typing: 'AI ბეჭდავს პასუხს...',
    ai_widget_send: 'გაგზავნა',

    // Footer
    footer_desc: 'შპს „ართრონი“ გთავაზობთ სპორტული ობიექტებისა და ფიტნეს დარბაზების მართვის უახლეს B2B SaaS ეკოსისტემას და B2C მობილურ აპლიკაციას.',
    footer_col_legal: 'იურიდიული',
    footer_col_contact: 'კონტაქტი',
    footer_company_id: 'შპს „ართრონი“ (ს/კ 412799431)',
    footer_address: 'საქართველო, ქუთაისი, ნიკეას ქ., N 46ა, ბ. 17',
    footer_cookie_prefs: 'ქუქი-ფაილების პარამეტრები',
    footer_all_rights: 'ყველა უფლება დაცულია.',

    // Legal Disclosures Header / Helpers
    legal_last_updated: 'ბოლო განახლება: 2026 წლის 10 აგვისტო',
    legal_back_to_home: '← მთავარ გვერდზე დაბრუნება',
    legal_toc_title: 'სარჩევი',
    legal_official_identifier: 'ოფიციალური რეკვიზიტები: შპს „ართრონი“ (ს/კ 412799431), საქართველო, ქუთაისი, ნიკეას ქ., N 46ა, ბ. 17 | info@artron.ge',

    // Privacy Policy
    privacy_title: 'კონფიდენციალურობის პოლიტიკა',
    privacy_subtitle: 'მონაცემთა დაცვა, შიფრაცია და ბიომეტრიული უსაფრთხოება ართრონის ეკოსისტემაში',
    privacy_sec_operator_title: '1. ოფიციალური ოპერატორი და კონტაქტი',
    privacy_sec_operator_body: 'მონაცემთა დამუშავების ოპერატორი არის შპს „ართრონი“ (საიდენტიფიკაციო კოდი: 412799431), იურიდიული მისამართი: საქართველო, ქუთაისი, ნიკეას ქ., N 46ა, ბ. 17. ოფიციალური საკონტაქტო არხი: info@artron.ge. ჩვენი კიბერუსაფრთხოებისა და მონაცემთა დაცვის გუნდი მუდმივად აკონტროლებს ინფორმაციულ ნაკადებს უსაფრთხოების უმაღლესი სტანდარტების დასაცავად.',
    privacy_sec_roles_title: '2. მონაცემთა დამმუშავებლისა და კონტროლერის როლები',
    privacy_sec_roles_body: 'შპს „ართრონი“ მოქმედებს როგორც ტექნიკური მონაცემთა დამმუშავებელი (Data Processor) B2B კლიენტების (სპორტული ობიექტების, დამსაქმებლების, ფედერაციების) მიერ ატვირთული მონაცემებისათვის (მაგ. თანამშრომელთა სამუშაო დროის აღრიცხვა ბრძანება №01-15/ნ-ის შესაბამისად, სამედიცინო კოდები, სპორტსმენთა რეესტრები). შპს „ართრონი“ მოქმედებს როგორც მონაცემთა კონტროლერი (Data Controller) მობილური აპლიკაციის პროფილების, ავტორიზაციის ინფორმაციისა და აპლიკაციის ლოგების დამუშავებისას.',
    privacy_sec_security_title: '3. მონაცემთა დაცვა და შიფრაციის სტანდარტები',
    privacy_sec_security_body: 'ყველა სენსიტიური პერსონალური საიდენტიფიკაციო ველი (მაგ. პირადი ნომერი - National ID) დაცულია AES-256-GCM სვეტის დონის შიფრაციით (Column-Level Encryption) შენახვისას (at rest). პაროლები იშიფრება უსაფრთხო ჰეშირების ალგორითმით (bcrypt/argon2). ფინანსური მონაცემები სრულად იზოლირებულია PCI-DSS სტანდარტების შესაბამისად; ბარათის მონაცემები არ ინახება ჩვენს სერვერებზე.',
    privacy_sec_biometrics_title: '4. ბიომეტრიული და სპეციალური კატეგორიის მონაცემები',
    privacy_sec_biometrics_body: 'ტურნიკეტის სისტემებში იდენტიფიკაციისთვის გამოყენებული პროფილის ფოტოები კლასიფიცირდება როგორც ბიომეტრიული მონაცემები. სამედიცინო ცნობები და სამუშაოდან გათავისუფლების კოდები (მაგ. საავადმყოფო ფურცელი) წარმოადგენს სპეციალური კატეგორიის ჯანმრთელობის მონაცემებს. მათი დამუშავება ხორციელდება მხოლოდ მკაცრი როლური წვდომის კონტროლისა (RBAC) და მომხმარებლის მკაფიო თანხმობის საფუძველზე.',
    privacy_sec_erasure_title: '5. მონაცემთა შენახვისა და წაშლის ვადები',
    privacy_sec_erasure_body: 'მობილური აპლიკაციიდან ან ელფოსტით მოთხოვნილი ანგარიშის წაშლა სრულდება 15 კალენდარულ დღეში. სპეციალური კატეგორიისა და ბიომეტრიული მონაცემები იშლება მოთხოვნიდან 5 კალენდარულ დღეში. საქართველოს საგადასახადო კოდექსის შესაბამისად, ფინანსური ტრანზაქციებისა და აბონემენტების შესყიდვის ლოგები ინახება საარქივო რეჟიმში 3 წლის განმავლობაში, რის შემდეგაც ხდება მათი სრული განადგურება.',
    privacy_sec_rights_title: '6. მონაცემთა სუბიექტის უფლებები',
    privacy_sec_rights_body: '„პერსონალურ მონაცემთა დაცვის შესახებ“ საქართველოს კანონისა და GDPR-ის შესაბამისად, თქვენ გაქვთ უფლება მოითხოვოთ წვდომა თქვენს მონაცემებზე, მათი შესწორება, წაშლა ან დამუშავების შეზღუდვა. ნებისმიერი კითხვის ან მოთხოვნის შემთხვევაში დაგვიკავშირდით info@artron.ge-ზე.',

    // Terms of Use
    terms_title: 'მომსახურების პირობები',
    terms_subtitle: 'ვებგვერდითა და ართრონის SaaS პლატფორმით სარგებლობის წესები',
    terms_sec_license_title: '1. სალიცენზიო ხელშეკრულება',
    terms_sec_license_body: 'შპს „ართრონი“ მომხმარებელს ანიჭებს შეზღუდულ, არაექსკლუზიურ, არაგადაცემად და გაუქმებად ლიცენზიას (SaaS Subscription) პლატფორმასთან წვდომისთვის. პლატფორმის კოდი, დიზაინი და სქემები წარმოადგენს შპს „ართრონის“ ექსკლუზიურ ინტელექტუალურ საკუთრებას. გამოწერის აქტივაცია არ გადასცემს მომხმარებელს საავტორო უფლებებს ან კოდის საკუთრებას.',
    terms_sec_security_title: '2. უსაფრთხოების წესები და შეზღუდვები',
    terms_sec_security_body: 'მომხმარებელს ეკრძალება სისტემის საპირისპირო ინჟინერია (reverse engineering), SQL/NoSQL ინექციების ან ნებისმიერი მავნე კოდის სისტემაში გაშვება. ყველა ფორმა გადის მკაცრ ვალიდაციას და სანიტარიზაციას. ნებისმიერი არაავტორიზებული ქმედება გამოიწვევს წვდომის მყისიერ დაბლოკვას.',
    terms_sec_refunds_title: '3. გადახდები და თანხის დაბრუნება (B2B & B2C)',
    terms_sec_refunds_body: 'საქართველოს კანონის „მომხმარებლის უფლებების დაცვის შესახებ“ შესაბამისად, მობილური აპლიკაციით შეძენილ მომსახურებაზე მოქმედებს 14-დღიანი უპირობო თანხის დაბრუნების (right of withdrawal) წესი, თუ სარგებლობა არ დაწყებულა. B2B სეგმენტში, სპორტული ობიექტები თავად წარმოადგენენ გადახდების მიმღებ ოფიციალურ სუბიექტებს და ვალდებულნი არიან დამოუკიდებლად უზრუნველყონ კანონით გათვალისწინებული დაბრუნების პროცედურები.',
    terms_sec_offboarding_title: '4. მომხმარებლის გამორთვა და საარქივო პერიოდი',
    terms_sec_offboarding_body: 'B2B ხელშეკრულების შეწყვეტისას, აქტიური საოპერაციო მონაცემები (სამუშაო გრაფიკები, კლიენტთა სიები) ინახება 30 კალენდარული დღის განმავლობაში მონაცემთა სრული ექსპორტისთვის, რის შემდეგაც იშლება live ბაზიდან. ფინანსური მონაცემები საქართველოს კანონმდებლობის შესაბამისად იბლოკება და ინახება უსაფრთხო არქივში 3 წლის განმავლობაში.',
    terms_sec_liability_title: '5. პასუხისმგებლობის შეზღუდვა',
    terms_sec_liability_body: 'შპს „ართრონი“ არ არის პასუხისმგებელი B2B კლიენტებისა და B2C წევრების ურთიერთობაზე, მათ შორის აბონემენტის ფარგლებში გაწეული ფიზიკური მომსახურების ხარისხზე. პლატფორმა მოწოდებულია „როგორც არის“ (as is) პრინციპით.',

    // Cookie Policy
    cookie_policy_title: 'ქუქი-ფაილების პოლიტიკა',
    cookie_policy_subtitle: 'ქუქი-ფაილების მართვის, თანხმობისა და უსაფრთხოების სტანდარტები',
    cookie_policy_sec_desc_title: '1. რა არის ქუქი-ფაილი?',
    cookie_policy_sec_desc_body: 'ქუქი-ფაილი არის მცირე ზომის ტექსტური ფაილი, რომელიც ინახება თქვენს მოწყობილობაზე საიტის სტუმრობისას. ის გვეხმარება ენის არჩევანის, სესიის იდენტიფიკაციისა და უსაფრთხოების პარამეტრების დამახსოვრებაში.',
    cookie_policy_sec_categories_title: '2. ქუქი-ფაილების კატეგორიები',
    cookie_policy_sec_categories_body: 'ჩვენ ვიყენებთ შემდეგი კატეგორიების ქუქიებს: 1. აუცილებელი (Strictly Necessary): სავალდებულოა საიტის ფუნქციონირებისთვის (მაგ. artron_cookie_consent, ენა, სესია) და არ საჭიროებს წინასწარ თანხმობას; 2. ანალიტიკური (Analytics): გვეხმარება საიტის ტრაფიკის გაზომვაში (Google Analytics); 3. მარკეტინგული (Marketing): გამოიყენება Google Ads და რემარკეტინგული მიზნებისთვის.',
    cookie_policy_sec_consent_title: '3. Google Consent Mode v2 და თანხმობა',
    cookie_policy_sec_consent_body: 'საიტზე დანერგილია Google Consent Mode v2. ნაგულისხმევად (by default), ანალიტიკური და მარკეტინგული ქუქი-ფაილები გათიშულია (\'denied\'). ისინი აქტიურდება მხოლოდ მას შემდეგ, რაც მომხმარებელი დაადასტურებს შესაბამის კატეგორიას ქუქი-ფაილების მართვის პანელში. IP მისამართების გადაცემა ხდება ანონიმიზებულ რეჟიმში.',
    cookie_policy_sec_apple_title: '4. Apple ATT და მობილური მოწყობილობები',
    cookie_policy_sec_apple_body: 'მობილური WebView-ებისა და iOS აპლიკაციებისათვის, ართრონი სრულად ითვალისწინებს Apple App Tracking Transparency (ATT) მოთხოვნებს. სისტემა არ აკონტროლებს მომხმარებლის ქცევას სხვა კომპანიების აპლიკაციებსა და ვებსაიტებზე წინასწარი ნებართვის გარეშე.',
    cookie_policy_sec_manage_title: '5. როგორ შევცვალოთ ქუქი-პარამეტრები?',
    cookie_policy_sec_manage_body: 'თქვენ ნებისმიერ დროს შეგიძლიათ შეცვალოთ თქვენი არჩევანი საიტის ქვედა ნაწილში (Footer) მოცემული ბმულის „ქუქი-ფაილების პარამეტრები“ მეშვეობით, რომელიც თავიდან გახსნის თანხმობის პანელს.',
    del_acc_title: 'ანგარიშის წაშლა',
    del_acc_subtitle: 'ანგარიშის დეაქტივაციისა და მონაცემთა წაშლის პროცედურა',
    del_acc_sec_overview_title: '1. მიმოხილვა და რეგულაციებთან შესაბამისობა',
    del_acc_sec_overview_body: 'Apple App Store-ისა და Google Play Store-ის სავალდებულო მოთხოვნების, ასევე „პერსონალურ მონაცემთა დაცვის შესახებ“ საქართველოს კანონის შესაბამისად, ARTRON-ის მომხმარებლებს აქვთ უფლება მოითხოვონ თავიანთი ანგარიშის და მასთან დაკავშირებული მონაცემების სრული წაშლა. წინამდებარე გვერდი აღწერს მონაცემთა წაშლის ორფაზიან პროტოკოლს და გაძლევთ შესაძლებლობას მოითხოვოთ ანგარიშის წაშლა პირდაპირ.',
    del_acc_sec_protocol_title: '2. მონაცემთა წაშლის ორფაზიანი პროტოკოლი',
    del_acc_sec_protocol_body: 'მონაცემთა წაშლა ხორციელდება შემდეგი ეტაპების მიხედვით: 1. მყისიერი დეაქტივაცია: მოთხოვნის დადასტურებისთანავე თქვენი ანგარიში დეაქტივირდება და გეზღუდებათ წვდომა სისტემასთან; 2. 15-დღიანი საშეღავათო პერიოდი: ამ პერიოდში შეგიძლიათ აღადგინოთ ანგარიში მხარდაჭერის გუნდთან დაკავშირებით; 3. 3-წლიანი საგადასახადო არქივი: საქართველოს საგადასახადო კოდექსისა და შრომის უსაფრთხოების ნორმების (მათ შორის ბრძანება №01-15/ნ) შესაბამისად, ფინანსური ტრანზაქციები და სამუშაო დროის აღრიცხვის ლოგები ინახება საარქივო რეჟიმში 3 წლის განმავლობაში, რის შემდეგაც ნადგურდება.',
    del_acc_sec_form_title: '3. ანგარიშის წაშლის მოთხოვნის ფორმა',
    del_acc_sec_form_body: 'შეავსეთ ქვემოთ მოცემული ფორმა ანგარიშის წაშლის პროცესის დასაწყებად. გთხოვთ მიუთითოთ რეგისტრირებული ელფოსტა ან ტელეფონის ნომერი და წაშლის მიზეზი.',
    del_acc_label_identity: 'რეგისტრირებული ელფოსტა ან ტელეფონის ნომერი',
    del_acc_placeholder_identity: 'user@artron.ge ან +995 599 123 456',
    del_acc_label_reason: 'ანგარიშის წაშლის მიზეზი',
    del_acc_placeholder_reason: 'გთხოვთ მოკლედ აღწეროთ მიზეზი (არასავალდებულო)',
    del_acc_check_grace: 'ვადასტურებ, რომ ანგარიშის დეაქტივაციის შემდეგ მაქვს 15-დღიანი საშეღავათო პერიოდი მის აღსადგენად.',
    del_acc_check_archival: 'ვადასტურებ, რომ მესმის 3-წლიანი საგადასახადო და სამუშაო დროის არქივის შენახვის პირობა.',
    del_acc_btn_submit: 'ანგარიშის წაშლის მოთხოვნა',
    del_acc_btn_submitting: 'მოთხოვნა იგზავნება...',
    del_acc_success_title: 'მოთხოვნა წარმატებით გაიგზავნა',
    del_acc_success_desc: 'თქვენი ანგარიშის წაშლის მოთხოვნა რეგისტრირებულია. ელფოსტაზე ან ტელეფონზე მიიღებთ ინსტრუქციას დეაქტივაციის დასადასტურებლად.',
    del_acc_error_identity: 'გთხოვთ მიუთითოთ ვალიდური ელფოსტა ან ტელეფონის ნომერი',
    del_acc_error_checkboxes: 'გთხოვთ დაადასტუროთ ორივე პირობა გაგრძელებამდე.',

    // B2B SaaS Agreement
    b2b_agreement_title: 'B2B SaaS სალიცენზიო ხელშეკრულება (MSA)',
    b2b_agreement_subtitle: 'სალიცენზიო და მომსახურების ხელშეკრულების ძირითადი პირობები შპს „ართრონსა“ და სპორტულ ცენტრებს/ფედერაციებს შორის',
    b2b_sec_scope_title: '1. მომსახურების სფერო და ფუნქციონალი',
    b2b_sec_scope_body: 'ხელშეკრულება მოიცავს წვდომას Artron B2B SaaS პლატფორმასთან, მათ შორის: 1) ადმინისტრაციულ მართვის პანელთან (SaaS Web Panel) სპორტული ობიექტებისა და პერსონალის სამართავად; 2) IoT ტურნიკეტების სარელეო API-სთან (IoT Turnstile Relay API) ფიზიკური წვდომის ავტომატური კონტროლისთვის; 3) B2C მობილურ აპლიკაციასთან (Athlete Mobile Integration) სპორტსმენებისა და წევრებისთვის, რომელიც ინტეგრირებულია ტურნიკეტის დინამიურ QR საშვებთან, ონლაინ გადახდებთან და აქტივობების კალენდართან.',
    b2b_sec_sla_title: '2. მომსახურების დონე (SLA) და ხელმისაწვდომობის გარანტია',
    b2b_sec_sla_body: 'შპს „ართრონი“ იღებს ვალდებულებას, უზრუნველყოს SaaS პლატფორმისა და API სერვერების 99.9%-იანი ყოველთვიური ხელმისაწვდომობა (Uptime Guarantee). გეგმური ტექნიკური სამუშაოების შესახებ, რომლებიც შეიძლება გავლენას ახდენდეს სისტემის მუშაობაზე, კლიენტებს ეცნობებათ მინიმუმ 24 საათით ადრე. ფორსმაჟორული სიტუაციები, კავშირგაბმულობის პროვაიდერების შეფერხებები ან კლიენტის ადგილობრივი ქსელის პრობლემები არ განიხილება Uptime გარანტიის დარღვევად.',
    b2b_sec_pricing_title: '3. საფასო ტარიფები და სააბონენტო ანგარიშსწორება',
    b2b_sec_pricing_body: 'პლატფორმით სარგებლობის საფასური განისაზღვრება არჩეული პაკეტის (Starter, Pro, Enterprise) შესაბამისად. სააბონენტო გადასახადი ირიცხება ყოველთვიურად ან ყოველწლიურად წინასწარი გადახდის (pre-paid) პრინციპით. გადახდის ვადა შეადგენს ყოველი ახალი საანგარიშო პერიოდის დაწყებიდან 5 კალენდარულ დღეს. საფასურის გადაუხდელობის შემთხვევაში, შპს „ართრონი“ იტოვებს უფლებას, დროებით შეზღუდოს წვდომა მართვის პანელთან და IoT ტურნიკეტების API-სთან.',
    b2b_sec_labor_title: '4. საქართველოს შრომის ინსპექციის მოთხოვნებთან შესაბამისობა (ბრძანება №01-15/ნ)',
    b2b_sec_labor_body: 'Artron-ის პლატფორმაში ინტეგრირებული სამუშაო დროის აღრიცხვის მოდული სრულად აკმაყოფილებს საქართველოს ოკუპირებული ტერიტორიებიდან დევნილთა, შრომის, ჯანმრთელობისა და სოციალური დაცვის მინისტრის ბრძანება №01-15/ნ მოთხოვნებს. სისტემა უზრუნველყოფს თანამშრომელთა შესვლა/გასვლის ავტომატურ აღრიცხვას IoT აპარატურის საშუალებით, სამუშაო საათების ზუსტ გაანგარიშებას და ელექტრონული ტაბელების გენერირებას, რაც აუცილებელია შრომის ინსპექციის შემოწმებების წარმატებით გავლისთვის.',
    b2b_sec_dpa_title: '5. მონაცემთა დამუშავების შეთანხმება (DPA) და შიფრაცია',
    b2b_sec_dpa_body: 'მონაცემთა დამუშავების ფარგლებში, შპს „ართრონი“ მოქმედებს როგორც ტექნიკური მონაცემთა დამმუშავებელი (Data Processor) B2B კლიენტის სახელით. მხარეები თანხმდებიან, რომ სენსიტიური ინფორმაცია, როგორიცაა სპორტსმენთა და თანამშრომელთა პირადი ნომრები (National IDs), ბაზაში ინახება დაცულად და იშიფრება AES-256-GCM სვეტის დონის შიფრაციის ალგორითმით. ბიომეტრიული ფოტოები და ჯანმრთელობის მონაცემები მუშავდება მხოლოდ როლური წვდომის კონტროლის (RBAC) და კანონმდებლობით გათვალისწინებული უსაფრთხოების წესების მკაცრი დაცვით.',
    b2b_sec_termination_title: '6. ხელშეკრულების შეწყვეტა, 30-დღიანი ექსპორტი და 3-წლიანი არქივი',
    b2b_sec_termination_body: 'ხელშეკრულების შეწყვეტის შემთხვევაში, კლიენტს ეძლევა 30 კალენდარული დღე საოპერაციო მონაცემების (ვიზიტების ისტორია, წევრთა სია, ცხრილები) სრული ექსპორტისთვის, რის შემდეგაც live ბაზაში არსებული საოპერაციო ინფორმაცია ნადგურდება. საქართველოს საგადასახადო კოდექსის მოთხოვნათა შესაბამისად, ფინანსური ტრანზაქციების ჟურნალები და სააბონენტო გადახდების ისტორია არ წაიშლება და შეინახება უსაფრთხო არქივში 3 წლის განმავლობაში საგადასახადო აუდიტის მიზნებისთვის.',

    // About Us Page
    about_title: 'ჩვენს შესახებ',
    about_subtitle: 'ავტომატიზაციის ლიდერი ფიტნეს & სპორტულ ინდუსტრიაში',
    about_mission_title: 'კომპანიის მისია',
    about_mission_body: 'ქართული ფიტნეს ცენტრებისა და სპორტული ფედერაციების ციფრული ტრანსფორმაცია, საოპერაციო ხარჯების ოპტიმიზაცია და მომხმარებელთა გამოცდილების გაუმჯობესება უახლესი ტექნოლოგიური გადაწყვეტილებების დანერგვით.',
    about_who_title: 'ვინ ვართ ჩვენ',
    about_who_body: 'ჩვენ ვართ საქართველოში ბაზირებული ექსპერტები IoT (ნივთების ინტერნეტი) აპარატურულ რელეებსა და cloud-native SaaS არქიტექტურაში. ვქმნით საიმედო, უსაფრთხო და მაღალტექნოლოგიურ სისტემებს სპორტული ობიექტების სრული ავტომატიზაციისთვის.',
    about_compliance_title: 'ლოკალური შესაბამისობა',
    about_compliance_body: 'სრული ინტეგრაცია საქართველოს იურიდიულ მოთხოვნებთან, მათ შორის შრომის ინსპექციის ბრძანება №01-15/ნ-თან (სამუშაო დროის აღრიცხვა) და ლოკალური 24/7 ტექნიკური მხარდაჭერა ქართულ ენაზე.',
    about_identity_title: 'ოფიციალური რეკვიზიტები',
    about_identity_body: 'შპს „ართრონი“ (საიდენტიფიკაციო კოდი: 412799431), იურიდიული მისამართი: საქართველო, ქუთაისი, ნიკეას ქ., N 46ა, ბ. 17. ოფიციალური საკონტაქტო არხი: info@artron.ge.',
    about_feat_support_title: 'ლოკალური მხარდაჭერა 24/7',
    about_feat_support_desc: 'გარანტირებული 24/7 მხარდაჭერა ქართულ ენაზე, სწრაფი რეაგირება და ადგილზე დახმარება ნებისმიერ დროს.',
    about_feat_iot_title: 'IoT აპარატურის საიმედოობა',
    about_feat_iot_desc: 'საკუთარი წარმოების სარელეო კონტროლერები და ტურნიკეტების ავტონომიური მუშაობა offline რეჟიმშიც კი.',
    about_feat_privacy_title: 'მონაცემთა დაცვა & AES-256-GCM',
    about_feat_privacy_desc: 'სენსიტიური ინფორმაციის სვეტის დონის შიფრაცია და მკაცრი როლური წვდომის კონტროლი (RBAC).',
    about_feat_legal_title: 'სრული იურიდიული შესაბამისობა',
    about_feat_legal_desc: 'შესაბამისობა შრომის ინსპექციის №01-15/ნ ბრძანებასთან და მომხმარებელთა უფლებების დაცვის კანონთან.',
    about_cta_title: 'მზად ხართ თქვენი დარბაზის ავტომატიზაციისთვის?',
    about_cta_desc: 'გამოსცადეთ ართრონის პლატფორმის ორმაგი ძალა — B2B მართვის პანელი და B2C მობილური აპლიკაცია.',
    about_cta_button: 'მოითხოვეთ უფასო დემო',

    // Dashboard Features Section
    dashboardFeatures_title: 'B2B ადმინისტრაციული პანელი',
    dashboardFeatures_subtitle: 'ფიტნეს საწარმოებისა და სპორტული ფედერაციების ძირითადი მართვის ცენტრი.',
    dashboardFeatures_feat1_title: 'რეალურ დროში IoT ტურნიკეტი & კარების კონტროლი',
    dashboardFeatures_feat1_desc: 'ავარიული განბლოკვა, ცოცხალი ტელემეტრია და TCP/UDP სარელეო მარშრუტიზაცია უსაფრთხო წვდომისთვის.',
    dashboardFeatures_feat2_title: 'წევრებისა და სპორტსმენების ბაზის მართვა',
    dashboardFeatures_feat2_desc: 'აბონემენტების სტატუსები, ინდივიდუალური ტარიფები და მყისიერი დინამიური QR საშვების გენერაცია.',
    dashboardFeatures_feat3_title: 'შრომის ინსპექციის ბრძანება №01-15/ნ ტაბელები',
    dashboardFeatures_feat3_desc: 'პერსონალის სამუშაო საათების ავტომატური აღრიცხვა, უსაფრთხო აუდიტის ლოგები და სრული შესაბამისობა.',
    dashboardFeatures_feat4_title: 'ფინანსური ანალიტიკა & Multi-Tenancy',
    dashboardFeatures_feat4_desc: 'შემოსავლების დინამიკა და მრავალი ფილიალის მართვა ერთიანი ავტორიზაციით (Single Sign-On).',
    
    // Mockup UI translations
    dashboardFeatures_panel_title: 'მართვის პანელი (B2B)',
    dashboardFeatures_panel_status: 'სისტემა აქტიურია',
    dashboardFeatures_gate_name: 'მთავარი შესასვლელი ტურნიკეტი',
    dashboardFeatures_emergency_btn: 'საავარიო გახსნა',
    dashboardFeatures_remote_unlock: 'დისტანციური გახსნა',
    dashboardFeatures_unlocked_pulse: 'გახსნილია 5 წამით',
    dashboardFeatures_locked_state: 'დაბლოკილია',
    dashboardFeatures_unlocked_state: 'განბლოკილია',
    dashboardFeatures_status: 'სტატუსი',
    dashboardFeatures_relay: 'UDP სარელეო მარშრუტიზაცია',
    dashboardFeatures_relay_on: 'აქტიური',
    dashboardFeatures_relay_off: 'გათიშული',
    dashboardFeatures_logs_title: 'ცოცხალი ტელემეტრიის ლოგი',
    dashboardFeatures_db_name: 'სახელი, გვარი',
    dashboardFeatures_db_status: 'აბონემენტი',
    dashboardFeatures_db_status_active: 'აქტიური',
    dashboardFeatures_db_tier: 'კატეგორია',
    dashboardFeatures_db_tier_vip: 'VIP წევრი',
    dashboardFeatures_db_id: 'პირადი ნომერი',
    dashboardFeatures_db_encrypted: 'დაშიფრულია (AES-256)',
    dashboardFeatures_db_qr: 'დინამიური QR საშვი',
    dashboardFeatures_db_qr_gen: 'გენერირება',
    dashboardFeatures_labor_title: 'სამუშაო დროის აღრიცხვა (ბრძანება №01-15/ნ)',
    dashboardFeatures_labor_audits: 'უსაფრთხო აუდიტის ლოგები',
    dashboardFeatures_labor_audits_show: 'ლოგების ჩვენება',
    dashboardFeatures_fin_revenue: 'ყოველკვირეული შემოსავალი',
    dashboardFeatures_fin_branches: 'ფილიალები',
    dashboardFeatures_fin_branch_tb: 'თბილისი ვაკე',
    dashboardFeatures_fin_branch_bt: 'ბათუმი ბულვარი',
    dashboardFeatures_fin_branch_kt: 'ქუთაისი ნიკეა',
    partner_title: 'ინტეგრირებული პარტნიორები',
    partner_subtitle: 'ართრონის ეკოსისტემა სინქრონიზებულია წამყვან ფინტექ და წვდომის კონტროლის სისტემებთან',
    partner_fintech: 'ფინტექი და ბილინგი',
    partner_access: 'წვდომის კონტროლი და აპარატურა',
    partner_iot: 'IoT და რელეები',
    booking_title: 'დაჯავშნეთ პირდაპირი დემო',
    booking_subtitle: 'გაიარეთ უფასო კონსულტაცია ჩვენს ინჟინრებთან და შეარჩიეთ თქვენზე მორგებული ავტომატიზაციის გეგმა',
    booking_map_hq: 'ARTRON ცენტრალური შტაბ-ბინა',
    booking_map_coords: 'მისამართი: ნიკეას ქ., N 46ა, ქუთაისი • 42.2496° N, 42.7015° E',
    booking_map_status: 'სტატუსი: აქტიური (ონლაინ)',
    booking_map_desc: 'ართრონის საოპერაციო ცენტრი და IoT აპარატურის საწარმოო ლაბორატორია.',
    booking_fallback_title: 'მოითხოვეთ დემო პრეზენტაცია',
    booking_fallback_name: 'სახელი და გვარი',
    booking_fallback_email: 'ელ-ფოსტა',
    booking_fallback_phone: 'ტელეფონის ნომერი',
    booking_fallback_type: 'ობიექტის ტიპი',
    booking_fallback_submit: 'პრეზენტაციის დაჯავშნა',
    booking_fallback_success: 'დემო მოთხოვნა წარმატებით დარეგისტრირდა! ჩვენი გუნდი მალე დაგიკავშირდებათ.',
    cta_title: 'გახადეთ თქვენი დარბაზი ჭკვიანი დღესვე',
    cta_subtitle: 'შეუერთდით სპორტული ობიექტების ახალ ეპოქას. დაზოგეთ დრო, შეამცირეთ ხარჯები და მართეთ ყველაფერი ცენტრალიზებულად.',
    cta_btn_book: 'დემოს დაჯავშნა (Cal.com)',
    cta_btn_register: 'დაარეგისტრირეთ დარბაზი',

    // Core Analytical Modules Copy
    analytics_kpi_title: '📊 KPI პანელი (ბიზნესის ჯანმრთელობის კონტროლი)',
    analytics_kpi_subtitle: 'რეალურ დროში ფინანსური და საოპერაციო მდგომარეობა',
    analytics_kpi_bullet1: '<strong>MRR & LTV მონიტორინგი</strong>: თვალყური ადევნეთ ყოველთვიურ განმეორებად შემოსავალს და კლიენტის სიცოცხლის ხანგრძლივობის ღირებულებას.',
    analytics_kpi_bullet2: '<strong>CAC ანალიზი</strong>: შეაფასეთ ახალი მომხმარებლის მოზიდვის რეალური ხარჯი მარკეტინგული არხების მიხედვით.',
    analytics_kpi_bullet3: '<strong>საოპერაციო მეტრიკები</strong>: აქტიური წევრების რაოდენობა, წმინდა ზრდის კოეფიციენტი და ვიზიტების დინამიკა.',
    analytics_market_title: '🌐 ბაზრისა და ქცევის ანალიტიკა',
    analytics_market_subtitle: 'მომხმარებელთა მოთხოვნის და დარბაზის დატვირთვის ანალიზი',
    analytics_market_bullet1: '<strong>დატვირთვის რუკა (Heatmaps)</strong>: დარბაზის დატვირთვის სითბური რუკა არაპიკური საათებისა და ფასდაკლებების დასაგეგმად.',
    analytics_market_bullet2: '<strong>დემოგრაფიული სეგმენტაცია</strong>: მომხმარებელთა განაწილება ასაკის, სქესის და ლოკაციის მიხედვით.',
    analytics_market_bullet3: '<strong>პაკეტების პოპულარობა</strong>: ყველაზე გაყიდვადი აბონემენტებისა და დამატებითი სერვისების (ფიტნეს-ბარი, პერსონალური ვარჯიში) რეიტინგი.',
    analytics_churn_title: '⚠️ AI Churn Prediction (გადინების პრევენცია)',
    analytics_churn_subtitle: 'გადინების პროგნოზირება მანქანური სწავლებით (ML)',
    analytics_churn_bullet1: '<strong>გადინების რისკის ქულა (0-100%)</strong>: თითოეული მომხმარებლის მიტოვების რისკის ინდივიდუალური შეფასება.',
    analytics_churn_bullet2: '<strong>ქცევითი ანომალიების ძებნა</strong>: ვიზიტების სიხშირის კლების მყისიერი დაფიქსირება (Drop-in-Frequency).',
    analytics_churn_bullet3: '<strong>AI Auto-Triggers</strong>: ავტომატური სამოტივაციო შეთავაზებებისა და SMS-ების გაგზავნა კლიენტის წასვლამდე.',
    analytics_winback_title: '🔄 Win-back Analytics (წასული წევრების დაბრუნება)',
    analytics_winback_subtitle: 'პასიური და დაკარგული კლიენტების რეაქტივაცია',
    analytics_winback_bullet1: '<strong>პასიურობის დონის სეგმენტაცია</strong>: ახალი პასიურები (14-30 დღე), საშუალო რისკი (30-60 დღე) და დაკარგულები (90+ დღე).',
    analytics_winback_bullet2: '<strong>Campaign ROI & A/B ტესტირება</strong>: SMS/Email კამპანიების ეფექტურობის ანალიზი (-15% ფასდაკლება vs უფასო პერსონალური ვარჯიში).',
    analytics_winback_bullet3: '<strong>Cost per Win-back vs CAC</strong>: დაბრუნების ხარჯის შედარება ახალი მომხმარებლის მოზიდვის ღირებულებასთან.',
    
    // Additional ROI Labels
    roi_price_label: 'აბონემენტის საშუალო ფასი',
  },
  en: {
    // Navbar / Header
    logo_text: 'ARTRON',
    logo_sub: 'Sports SaaS & IoT',
    lang_selector: 'Language',
    nav_ecosystem: 'Ecosystem',
    nav_roi: 'ROI Calculator',
    nav_partners: 'Partners',
    nav_booking: 'Book Demo',
    nav_faq: 'FAQ',

    // Hero Section
    hero_badge: 'DUAL-CORE SHOWCASE • B2B + B2C INTEGRATION',
    hero_title_1: 'Sports & Fitness',
    hero_title_gradient: 'Automation Ecosystem',
    hero_subtitle: 'The ultimate sports facility & gym management platform: Unify B2B CRM dashboard with B2C mobile apps. Free your reception desk with 24/7 automated IoT turnstiles, ensure 100% legal compliance with automated employee work-time tracking (Order №01-15/ნ), and boost revenue via an online marketplace for subscriptions, single passes, and trainer packages.',
    cta_b2b: 'Request B2B Demo',
    cta_b2c: 'Explore Mobile App',

    // Hero Stats
    stat_admin_title: '30% Less Time',
    stat_admin_desc: 'On administrative work',
    stat_access_title: '24/7 Automation',
    stat_access_desc: 'IoT turnstile control',
    stat_bookings_title: '0% Lost Bookings',
    stat_bookings_desc: 'Via automated AI campaigns',

    // Dashboard Preview (B2B)
    db_title: 'ARTRON Control Panel',
    db_status: 'IoT Controller Online',
    db_kpi_members: 'Active Members',
    db_kpi_entries: 'Daily Entries',
    db_kpi_winback: 'Win-Back Rate',
    db_logs_title: 'Live Turnstile Telemetry',
    db_log_in: 'Entered',
    db_log_out: 'Exited',
    db_user: 'User',
    db_employee_time: 'Work Hours (Order №01-15/ნ)',
    db_toggle_live: 'Live Telemetry',
    db_toggle_screenshot: 'Dashboard UI',
    db_screenshot_alt: 'Control Panel Dashboard UI',
    db_screenshot_zoom: 'Click image to expand',

    // Business Stats Showcase Section
    stats_sec_title: 'Control Panel Analytics: Real Business Metrics',
    stats_sec_subtitle: 'Artron collects and analyzes thousands of operational signals to help you increase gym financial and organizational efficiency.',
    stats_card_ltv_title: 'Client Retention (LTV & Win-Back)',
    stats_card_ltv_metric: '+22%',
    stats_card_ltv_sub: 'Recovered Members',
    stats_card_ltv_feat1: 'Instant Cron Campaigns',
    stats_card_ltv_feat2: 'Reduced Churn Rate',
    stats_card_ltv_feat3: 'Recovered Monthly Revenue',
    stats_card_iot_title: 'IoT Access Automation',
    stats_card_iot_metric: '-45h',
    stats_card_iot_sub: 'Admin Time Saved Weekly',
    stats_card_iot_feat1: '100% Autonomous Turnstiles',
    stats_card_iot_feat2: 'Zero Front-Desk Dependency',
    stats_card_iot_feat3: 'Secure Anti-Passback Control',
    stats_card_labor_title: 'Labor Compliance (Order №01-15/ნ)',
    stats_card_labor_metric: '100%',
    stats_card_labor_sub: 'Audit Pass Rate',
    stats_card_labor_feat1: 'Automated Log Timesheets',
    stats_card_labor_feat2: 'Labor Inspection Proof',
    stats_card_labor_feat3: 'Avoided Penalty Fines',
    stats_card_trainers_title: 'Trainer Sales & Commissions',
    stats_card_trainers_metric: '+35%',
    stats_card_trainers_sub: 'Increase in Package Sales',
    stats_card_trainers_feat1: 'In-App Online Marketplace',
    stats_card_trainers_feat2: 'Zero Calendar Conflicts',
    stats_card_trainers_feat3: 'Automated Commission Ledgers',

    // Mobile Preview (B2C)
    mobile_title: 'ARTRON Mobile App',
    mobile_welcome: 'Welcome back, Athlete!',
    mobile_qr_pass: 'Dynamic QR Pass',
    mobile_qr_desc: 'Scan at the turnstile gate',
    mobile_sub_status: 'My Subscription',
    mobile_sub_active: 'Active • 14 days left',
    mobile_progress: 'My Progress',
    mobile_workouts: 'Completed Workouts',
    mobile_nfc_desc: 'NFC Pass Enabled',

    // Cookie Banner
    cookie_title: 'Cookie & Consent Settings',
    cookie_desc: 'Artron LLC (ID: 412799431, Kutaisi, Nikea st., N 46A, apt. 17, info@artron.ge) uses cookies to optimize your browsing experience, perform analytics, and deliver targeted marketing in compliance with Google Consent Mode v2.',
    cookie_accept_all: 'Accept All',
    cookie_decline_all: 'Decline All',
    cookie_settings: 'Settings',
    cookie_save: 'Save Selection',
    cookie_necessary_title: 'Strictly Necessary',
    cookie_necessary_desc: 'Essential for browsing and security (sessions, locale, CSRF). Consent not required.',
    cookie_analytics_title: 'Analytics',
    cookie_analytics_desc: 'Allows us to measure site traffic and user behavior patterns (Google Analytics).',
    cookie_marketing_title: 'Marketing & Ads',
    cookie_marketing_desc: 'Used for personalization of ads, remarketing, and Google Ads metrics.',
    cookie_policy_link: 'Privacy & Cookie Policy',

    // Services Section
    services_section_title: 'Services Ecosystem',
    services_section_subtitle: 'The Dual-Core Power of Artron — One Platform for Admins and Athletes',
    services_tab_b2b: 'B2B Business Infrastructure',
    services_tab_b2c: 'B2C Mobile App',
    service_iot_title: 'IoT Hardware Integration',
    service_iot_desc: 'Direct TCP/Socket integration with smart turnstiles, biometric and NFC readers. 24/7 automated access control without front-desk staff.',
    service_worktime_title: 'Automated Work-Time Tracking (Order №01-15/ნ)',
    service_worktime_desc: 'Fully compliant with Georgian Labor Inspection guidelines. Biometric clock-in/out, automated timesheets, and easy export.',
    service_worktime_short: 'Work Hours (Order №01-15/ნ)',
    service_federation_title: 'Federation Management',
    service_federation_desc: 'Centralized platform for licenses, athlete registries, and event scheduling. Bridge between federations, clubs, and sports profiles.',
    service_marketplace_title: 'Membership Marketplace',
    service_marketplace_desc: 'Sell subscriptions, personal training packages, and inventory items online. Integrated 14-day statutory refund logic.',
    service_passbook_title: 'Mobile Passbook & QR Pass',
    service_passbook_desc: 'Secure gym access via dynamic, self-regenerating QR codes or NFC credentials. Eliminates card sharing and manual scanning.',
    service_metrics_title: 'Sports Metrics & Progress',
    service_metrics_desc: 'Visit calendar, workout history, athletic progress tracking, and trainer rating sync in real-time.',

    // ROI Calculator
    roi_title: 'B2B ROI Calculator',
    roi_subtitle: 'Calculate the financial and operational return of implementing Artron in your facility',
    roi_members_label: 'Active Members',
    roi_staff_label: 'Staff & Trainers',
    roi_time_saved_title: 'Time Saved',
    roi_time_saved_desc: 'hours/month saved on check-ins & timesheets',
    roi_revenue_title: 'Revenue Increase',
    roi_revenue_desc: 'annual growth from mobile sales & retention',
    roi_overhead_title: 'Overhead Reduction',
    roi_overhead_desc: 'monthly savings in administrative costs',
    roi_cta: 'Book a Free Demo Presentation',

    // FAQ Section
    faq_title: 'Frequently Asked Questions',
    faq_subtitle: 'Get answers regarding the Artron platform, IoT hardware setup, and legal compliance',
    faq_tab_all: 'All Questions',
    faq_tab_b2b: 'For B2B Businesses',
    faq_tab_b2c: 'For B2C Athletes',
    faq_q1: 'How long does IoT turnstile installation take?',
    faq_a1: 'Physical installation and network configuration are typically completed within 1-3 business days. Our team provides full technical setup and seamless integration with the ARTRON SaaS platform.',
    faq_q2: 'How is data security and multi-tenancy isolation guaranteed?',
    faq_a2: 'Each client\'s (tenant\'s) data is strictly isolated at both logical and database levels. Sensitive personal data (e.g., National ID) is encrypted using AES-256-GCM algorithm.',
    faq_q3: 'Does the work-time tracking comply with Georgian legislation (Order №01-15/ნ)?',
    faq_a3: 'Yes, Artron\'s work-time tracking module fully complies with the requirements of Order №01-15/n of the Minister of Internally Displaced Persons from the Occupied Territories, Labour, Health and Social Affairs of Georgia. The system automatically generates digital timesheets for Labor Inspection audits.',
    faq_q4: 'What happens if we terminate our subscription? How is data exported (30-day rule)?',
    faq_a4: 'Upon subscription termination, operational data is retained for 30 calendar days for full export by the tenant. After 30 days, the data is permanently purged, except for financial transaction logs, which are securely archived for 3 years to comply with the Tax Code of Georgia.',
    faq_q5: 'Does the 14-day refund window apply to subscriptions purchased via the mobile app?',
    faq_a5: 'Yes, in accordance with the Georgian Law \'On the Protection of Consumer Rights\', a statutory 14-day right of withdrawal and refund applies to mobile app subscriptions, provided the service utilization has not commenced.',
    faq_q6: 'How secure is the mobile QR pass? Can it be shared with others?',
    faq_a6: 'ARTRON\'s mobile QR pass is dynamic and automatically regenerates every 15 seconds. Screenshots cannot be used, which completely eliminates unauthorized pass sharing with third parties.',
    faq_q7: 'Does the turnstile gate work during internet outages (Offline mode)?',
    faq_a7: 'Yes, the turnstile controllers store a local cache of active credentials. Even in the event of an internet outage, authorized members and staff can enter offline, and all entrance logs will synchronize once connection is restored.',

    // AI Bot Widget
    ai_widget_launcher: 'Ask AI Assistant',
    ai_widget_title: 'ARTRON AI Assistant',
    ai_widget_subtitle: 'Online • Replies instantly',
    ai_widget_placeholder: 'Type your question here...',
    ai_widget_welcome: 'Hello! I am Artron\'s intelligent assistant. How can I help you today?',
    ai_widget_quick_1: 'Turnstile Setup',
    ai_widget_quick_2: 'Work Hours (Order №01-15/ნ)',
    ai_widget_quick_3: 'Refund Policy',
    ai_widget_typing: 'AI is typing response...',
    ai_widget_send: 'Send',

    // Footer
    footer_desc: 'Artron LLC provides a state-of-the-art B2B SaaS ecosystem and B2C mobile app for managing sports complexes and fitness clubs.',
    footer_col_legal: 'Legal',
    footer_col_contact: 'Contact Us',
    footer_company_id: 'Artron LLC (ID: 412799431)',
    footer_address: '46A Nikea St., Apt. 17, Kutaisi, Georgia',
    footer_cookie_prefs: 'Cookie Preferences',
    footer_all_rights: 'All rights reserved.',

    // Legal Disclosures Header / Helpers
    legal_last_updated: 'Last Updated: August 10, 2026',
    legal_back_to_home: '← Back to Home',
    legal_toc_title: 'Table of Contents',
    legal_official_identifier: 'Official Identity: Artron LLC (ID: 412799431), Georgia, Kutaisi, Nikea St., No. 46A, Apt. 17 | info@artron.ge',

    // Privacy Policy
    privacy_title: 'Privacy Policy',
    privacy_subtitle: 'Data protection, encryption, and biometric safety in the Artron ecosystem',
    privacy_sec_operator_title: '1. Official Operator and Contact',
    privacy_sec_operator_body: 'The data processor is Artron LLC (Identification Code: 412799431), registered legal address: 46A Nikea St., Apt. 17, Kutaisi, Georgia. Contact email: info@artron.ge. Our cybersecurity and data protection team continuously audits our information systems to ensure the highest standards of data safety.',
    privacy_sec_roles_title: '2. Data Processor and Data Controller Roles',
    privacy_sec_roles_body: 'Artron LLC acts as a Technical Data Processor for information uploaded by B2B clients (fitness clubs, employers, sports complexes) including employee timesheets under Ministerial Order №01-15/n, medical codes, and athlete registries. Artron LLC acts as a Data Controller for mobile app profile fields, credentials, configurations, and system logs.',
    privacy_sec_security_title: '3. Data Protection and Encryption Standards',
    privacy_sec_security_body: 'All sensitive personal identifiers (such as National ID numbers) are encrypted at rest using the AES-256-GCM column-level algorithm. Passwords are encrypted using robust hashing algorithms (bcrypt/argon2). Payment processing complies fully with PCI-DSS standards; credit card data is never stored on our local servers.',
    privacy_sec_biometrics_title: '4. Biometric and Special Category Data',
    privacy_sec_biometrics_body: 'Photos used for turnstile gate verification are classified as Biometric Data. Medical clearance records and health codes (such as leave information) represent special category health data. Their processing is restricted by strict role-based access controls (RBAC) and requires the user\'s explicit consent.',
    privacy_sec_erasure_title: '5. Retention and Deletion Timelines',
    privacy_sec_erasure_body: 'Standard user account deletions requested via the app or email are fully purged from production databases within 15 calendar days. Biometric photos and special category health data are purged within 5 calendar days. Under the Tax Code of Georgia, transaction records are safely archived for 3 years before permanent disposal.',
    privacy_sec_rights_title: '6. Rights of the Data Subject',
    privacy_sec_rights_body: 'In accordance with the Georgian Law \"On Personal Data Protection\" and GDPR, you have the right to request access, correction, deletion, or restriction of your personal data. For requests and inquires, please contact info@artron.ge.',

    // Terms of Use
    terms_title: 'Terms of Use',
    terms_subtitle: 'Rules and regulations for using the Artron website and SaaS ecosystem',
    terms_sec_license_title: '1. SaaS Subscription License',
    terms_sec_license_body: 'Artron LLC grants users a limited, non-exclusive, non-transferable, and revocable license to access the platform via subscription. The platform source code, structure, schemas, and assets remain the exclusive intellectual property of Artron LLC. Subscriptions grant system access only and do not transfer copyright or code ownership.',
    terms_sec_security_title: '2. Security Restrictions',
    terms_sec_security_body: 'Users are strictly prohibited from reverse-engineering the platform, attempting SQL/NoSQL injections, or deploying malicious payloads. Inputs are sanitized and validated. Violating actions will result in immediate termination of access.',
    terms_sec_refunds_title: '3. Payments and B2C/B2B Refund Policies',
    terms_sec_refunds_body: 'Under the Georgian Law \"On the Protection of Consumer Rights\", a 14-day statutory right of withdrawal and refund applies to mobile app subscriptions, provided service utilization has not commenced. For B2B clients, the sports facility acts as the seller of record for memberships and must manage statutory refunds independently.',
    terms_sec_offboarding_title: '4. Offboarding and Deactivation Retention',
    terms_sec_offboarding_body: 'When a B2B subscription is terminated, active operational data (schedules, customer lists) is retained for 30 calendar days to enable complete export, after which it is permanently purged. Financial logs are archived for 3 years in accordance with tax audit requirements.',
    terms_sec_liability_title: '5. Limitation of Liability',
    terms_sec_liability_body: 'Artron LLC is not responsible for the contractual or physical relationship between B2B facilities and B2C athletes, including the quality of physical training. The platform is provided on an \"as is\" basis.',

    // Cookie Policy
    cookie_policy_title: 'Cookie Policy',
    cookie_policy_subtitle: 'Cookie categories, consent triggers, and security compliance',
    cookie_policy_sec_desc_title: '1. What are Cookies?',
    cookie_policy_sec_desc_body: 'Cookies are small text files stored on your device when you visit our website. They help us remember your selected language, session identifier, and security settings.',
    cookie_policy_sec_categories_title: '2. Cookie Categories',
    cookie_policy_sec_categories_body: 'We utilize: 1. Strictly Necessary Cookies (e.g. artron_cookie_consent, session, language) which are essential for site functionality and do not require prior consent; 2. Analytics Cookies (e.g. Google Analytics) to measure site performance and visitor behavior; 3. Marketing Cookies (e.g. Google Ads) to personalize advertising.',
    cookie_policy_sec_consent_title: '3. Google Consent Mode v2',
    cookie_policy_sec_consent_body: 'The website implements Google Consent Mode v2. By default, analytics and marketing cookies are set to \"denied\". They are only updated to \"granted\" when you select them in our Cookie Settings panel. All IP tracking is anonymized before collection.',
    cookie_policy_sec_apple_title: '4. Apple ATT WebView Compliance',
    cookie_policy_sec_apple_body: 'For iOS web views and mobile apps, Artron adheres to Apple App Tracking Transparency (ATT) guidelines. We do not track user behavior across third-party websites or apps without explicit device-level authorization.',
    cookie_policy_sec_manage_body: 'You can update or withdraw your consent preferences at any time by clicking the \"Cookie Preferences\" link in the Footer, which reopens the consent management panel.',
    del_acc_title: 'Account Deletion',
    del_acc_subtitle: 'Procedure for account deactivation and data erasure',
    del_acc_sec_overview_title: '1. Overview & Regulatory Compliance',
    del_acc_sec_overview_body: 'In compliance with Apple App Store and Google Play Store mandatory deletion policies, as well as the Georgian Law \"On Personal Data Protection\", ARTRON users have the right to request the complete deletion of their account and associated data. This page outlines our two-phase erasure protocol and allows you to initiate the deletion process directly.',
    del_acc_sec_protocol_title: '2. Two-Phase Erasure Protocol',
    del_acc_sec_protocol_body: 'Data erasure follows these stages: 1. Immediate Deactivation: Upon submission, your account is deactivated and access is suspended; 2. 15-day Grace Period: You may recover your account within 15 calendar days by contacting our support team; 3. 3-year Statutory Archival: According to the Tax Code of Georgia and Labor Inspection standards (including Ministerial Order №01-15/n), financial transactions and work-time logs are archived securely for 3 years before final deletion.',
    del_acc_sec_form_title: '3. Account Deletion Request Form',
    del_acc_sec_form_body: 'Fill out the form below to initiate the account deletion process. Please specify your registered email or phone number and the reason for deletion.',
    del_acc_label_identity: 'Registered Email or Phone Number',
    del_acc_placeholder_identity: 'user@artron.ge or +995 599 123 456',
    del_acc_label_reason: 'Reason for Deletion',
    del_acc_placeholder_reason: 'Please briefly describe the reason (optional)',
    del_acc_check_grace: 'I confirm that I understand the 15-day grace period for account recovery.',
    del_acc_check_archival: 'I acknowledge the 3-year statutory tax and work-time archival requirement.',
    del_acc_btn_submit: 'Request Account Deletion',
    del_acc_btn_submitting: 'Submitting request...',
    del_acc_success_title: 'Request Submitted Successfully',
    del_acc_success_desc: 'Your account deletion request has been registered. You will receive an email or SMS with instructions to confirm deactivation.',
    del_acc_error_identity: 'Please provide a valid email address or phone number',
    del_acc_error_checkboxes: 'Please accept both terms to proceed.',

    // B2B SaaS Agreement
    b2b_agreement_title: 'B2B SaaS Master Services Agreement (MSA)',
    b2b_agreement_subtitle: 'Master Service Agreement and licensing terms between Artron LLC and tenant gyms/federations',
    b2b_sec_scope_title: '1. Scope of Service and Functionality',
    b2b_sec_scope_body: 'This agreement governs access to the Artron B2B SaaS platform, which includes: 1) the Administrator Control Panel (SaaS Web Panel) for managing sports facilities, trainer commissions, and staff schedules; 2) the IoT Turnstile Relay API for hardware integrations and real-time physical access control; 3) the Integrated Athlete Mobile App (B2C Mobile Integration) enabling dynamic QR passes, instant booking, and online subscriptions for members.',
    b2b_sec_sla_title: '2. Service Level Agreement (SLA) & 99.9% Uptime Guarantee',
    b2b_sec_sla_body: 'Artron LLC guarantees a 99.9% monthly server uptime for all SaaS services and API endpoints. In the event of planned maintenance that might impact performance, tenants will receive a notification at least 24 hours in advance. Force majeure, local network failures at the tenant\'s venue, or global internet routing outages are excluded from the uptime calculation.',
    b2b_sec_pricing_title: '3. Pricing Tiers & Subscription Billing',
    b2b_sec_pricing_body: 'Access fees are structured based on the selected tier (Starter, Pro, Enterprise) as agreed upon onboarding. Subscriptions are billed on a recurring monthly or annual pre-paid cycle. Payment is due within 5 calendar days of the new billing period. Failure to pay will result in a temporary suspension of both the SaaS control panel access and IoT turnstile sync.',
    b2b_sec_labor_title: '4. Compliance with Georgian Labor Inspection Order №01-15/ნ',
    b2b_sec_labor_body: 'Artron\'s integrated employee time-tracking module is fully compliant with Order №01-15/n of the Minister of Labour, Health and Social Affairs of Georgia. The system automatically records check-in and check-out events via physical IoT controllers, computes exact work hours, and generates standardized electronic timesheets required for labor inspection audits.',
    b2b_sec_dpa_title: '5. Data Processing Agreement (DPA) & Encryption Standards',
    b2b_sec_dpa_body: 'Under this agreement, Artron acts strictly as the Data Processor for all athlete and staff records uploaded by the Tenant (the Data Controller). To ensure maximum security, all athlete Personal Identifiers (National IDs) are encrypted at rest using AES-256-GCM column-level encryption. Biometric verification photos and health clearance certificates are managed under strict Role-Based Access Control (RBAC) schemas.',
    b2b_sec_termination_title: '6. Termination, 30-Day Offboarding Export, & 3-Year Archival',
    b2b_sec_termination_body: 'Upon termination of services, the tenant has 30 calendar days to export all operational datasets (member rosters, check-in history, staff logs). After 30 days, operational data is permanently deleted from live servers. However, in compliance with the Tax Code of Georgia, all financial transaction logs and subscription billing history must be securely archived for 3 years before final deletion.',

    // About Us Page
    about_title: 'About Us',
    about_subtitle: 'The Automation Leader in the Fitness & Sports Industry',
    about_mission_title: 'Company Mission',
    about_mission_body: 'Digital transformation of Georgian fitness centers and sports federations, optimizing operational overhead, and enhancing client experiences through modern technology.',
    about_who_title: 'Who We Are',
    about_who_body: 'We are Georgia-based experts in IoT (Internet of Things) hardware relays and cloud-native SaaS architecture, building reliable and scalable systems for the sports industry.',
    about_compliance_title: 'Local Compliance Advantage',
    about_compliance_body: 'Full integration with Georgian legal requirements, including Labor Inspection Order №01-15/ნ (work-time tracking) and local 24/7 technical support in Georgian.',
    about_identity_title: 'Company Identity Details',
    about_identity_body: 'Artron LLC (ID: 412799431), Legal Address: Georgia, Kutaisi, Nikea st., No. 46A, apt. 17. Official contact channel: info@artron.ge.',
    about_feat_support_title: '24/7 Local Support',
    about_feat_support_desc: 'Guaranteed 24/7 support in Georgian language, with fast response times and on-site assistance.',
    about_feat_iot_title: 'IoT Hardware Reliability',
    about_feat_iot_desc: 'In-house manufactured relay controllers and autonomous turnstile operations even in offline mode.',
    about_feat_privacy_title: 'Data Privacy & AES-256-GCM',
    about_feat_privacy_desc: 'Column-level encryption of sensitive identifiers (National ID) and secure role-based access.',
    about_feat_legal_title: 'Legal Compliance',
    about_feat_legal_desc: 'Compliance with Labor Inspection Order №01-15/ნ and Georgian B2C consumer rights protection regulations.',
    about_cta_title: 'Ready to Automate Your Sports Facility?',
    about_cta_desc: 'Experience the dual-core power of Artron - B2B management panel and B2C mobile application.',
    about_cta_button: 'Request Free Demo',

    // Dashboard Features Section
    dashboardFeatures_title: 'B2B Admin Dashboard',
    dashboardFeatures_subtitle: 'The core command center for fitness enterprises and sports federations.',
    dashboardFeatures_feat1_title: 'Real-Time IoT Turnstile & Door Control',
    dashboardFeatures_feat1_desc: 'Emergency unlock, live telemetry, and TCP/UDP relay routing for secure facility access.',
    dashboardFeatures_feat2_title: 'Member & Athlete Database Management',
    dashboardFeatures_feat2_desc: 'Subscription status tracking, custom pricing tiers, and instant dynamic QR pass generation.',
    dashboardFeatures_feat3_title: 'Labor Inspection Order №01-15/ნ Work-Hour Sheets',
    dashboardFeatures_feat3_desc: 'Automated staff time tracking, secure audit logs, and full compliance with Georgian labor standards.',
    dashboardFeatures_feat4_title: 'Financial Analytics & Multi-Tenancy',
    dashboardFeatures_feat4_desc: 'Revenue tracking, dynamic financial charts, and multi-branch control under a single sign-on.',

    // Mockup UI translations
    dashboardFeatures_panel_title: 'Operator Console (B2B)',
    dashboardFeatures_panel_status: 'System Online',
    dashboardFeatures_gate_name: 'Main Entrance Turnstile',
    dashboardFeatures_emergency_btn: 'Emergency Unlock',
    dashboardFeatures_remote_unlock: 'Remote Unlock',
    dashboardFeatures_unlocked_pulse: 'Unlocked for 5s',
    dashboardFeatures_locked_state: 'Locked',
    dashboardFeatures_unlocked_state: 'Unlocked',
    dashboardFeatures_status: 'Status',
    dashboardFeatures_relay: 'UDP Relay Routing',
    dashboardFeatures_relay_on: 'Active',
    dashboardFeatures_relay_off: 'Disabled',
    dashboardFeatures_logs_title: 'Live Telemetry Logs',
    dashboardFeatures_db_name: 'Full Name',
    dashboardFeatures_db_status: 'Subscription',
    dashboardFeatures_db_status_active: 'Active',
    dashboardFeatures_db_tier: 'Tier',
    dashboardFeatures_db_tier_vip: 'VIP Member',
    dashboardFeatures_db_id: 'Personal ID',
    dashboardFeatures_db_encrypted: 'Encrypted (AES-256)',
    dashboardFeatures_db_qr: 'Dynamic QR Pass',
    dashboardFeatures_db_qr_gen: 'Generate Pass',
    dashboardFeatures_labor_title: 'Work-Hour Sheets (Order №01-15/ნ)',
    dashboardFeatures_labor_audits: 'Secure Audit Logs',
    dashboardFeatures_labor_audits_show: 'Show Cryptographic Logs',
    dashboardFeatures_fin_revenue: 'Weekly Revenue',
    dashboardFeatures_fin_branches: 'Branches',
    dashboardFeatures_fin_branch_tb: 'Tbilisi Vake',
    dashboardFeatures_fin_branch_bt: 'Batumi Boulevard',
    dashboardFeatures_fin_branch_kt: 'Kutaisi Nikea',
    partner_title: 'Integrated Partners & Ecosystem',
    partner_subtitle: 'Artron ecosystem seamlessly integrates with leading FinTech and access control systems',
    partner_fintech: 'FinTech & Billing',
    partner_access: 'Access Control & Hardware',
    partner_iot: 'IoT & Relay Core',
    booking_title: 'Book a Live Demo Meeting',
    booking_subtitle: 'Consult with our system architects to choose the optimal automation configuration',
    booking_map_hq: 'ARTRON Central Headquarters',
    booking_map_coords: 'Address: Nikea St. N 46A, Kutaisi • 42.2496° N, 42.7015° E',
    booking_map_status: 'Status: Active (Online)',
    booking_map_desc: 'Artron operations command center and IoT hardware development laboratory.',
    booking_fallback_title: 'Request Demo Presentation',
    booking_fallback_name: 'Full Name',
    booking_fallback_email: 'Email Address',
    booking_fallback_phone: 'Phone Number',
    booking_fallback_type: 'Facility Type',
    booking_fallback_submit: 'Book Presentation',
    booking_fallback_success: 'Demo request submitted successfully! Our team will contact you shortly.',
    cta_title: 'Make Your Facility Smart Today',
    cta_subtitle: 'Join the new era of automated fitness operations. Save time, cut overheads, and govern everything in one console.',
    cta_btn_book: 'Book Live Demo (Cal.com)',
    cta_btn_register: 'Register Facility Now',

    // Core Analytical Modules Copy
    analytics_kpi_title: '📊 KPI Dashboard (Business Health Control)',
    analytics_kpi_subtitle: 'Real-time financial and operational metrics',
    analytics_kpi_bullet1: '<strong>MRR & LTV Monitoring</strong>: Track monthly recurring revenue and customer lifetime value in real-time.',
    analytics_kpi_bullet2: '<strong>CAC Analytics</strong>: Evaluate the actual customer acquisition cost across marketing channels.',
    analytics_kpi_bullet3: '<strong>Operational Metrics</strong>: Total active members, net growth rate, and daily check-in frequencies.',
    analytics_market_title: '🌐 Market & Behavior Analytics',
    analytics_market_subtitle: 'Analysis of customer demand and facility capacity',
    analytics_market_bullet1: '<strong>Capacity & Heatmaps</strong>: Traffic heatmaps to identify off-peak hours and design discount incentives.',
    analytics_market_bullet2: '<strong>Demographic Segmentation</strong>: Member distribution based on age groups, gender, and home locations.',
    analytics_market_bullet3: '<strong>Package Performance</strong>: Rankings of top-selling subscriptions and auxiliary services (fitness bar, personal trainers).',
    analytics_churn_title: '⚠️ AI Churn Prediction (Retention Guard)',
    analytics_churn_subtitle: 'Machine learning models forecasting customer churn',
    analytics_churn_bullet1: '<strong>Churn Risk Score (0-100%)</strong>: Individual risk score calculated for each member.',
    analytics_churn_bullet2: '<strong>Behavioral Anomaly Detection</strong>: Instant logging of check-in frequency drops (Drop-in-Frequency).',
    analytics_churn_bullet3: '<strong>AI Auto-Triggers</strong>: Automatic delivery of motivational offers and SMS before the customer decides to leave.',
    analytics_winback_title: '🔄 Win-back Analytics (Lost Member Reactivation)',
    analytics_winback_subtitle: 'Re-engaging passive and lapsed customers',
    analytics_winback_bullet1: '<strong>Inactivity Segmentation</strong>: Fresh lapsed (14-30 days), medium risk (30-60 days), and lost (90+ days).',
    analytics_winback_bullet2: '<strong>Campaign ROI & A/B Testing</strong>: Tracking response rates for reactivating campaigns (-15% discount vs. free personal training).',
    analytics_winback_bullet3: '<strong>Cost per Win-back vs. CAC</strong>: Comparing customer win-back cost directly with new client acquisition cost.',
    
    // Additional ROI Labels
    roi_price_label: 'Average Subscription Price',
  },
  ru: {
    // Navbar / Header
    logo_text: 'ARTRON',
    logo_sub: 'Спорт SaaS и IoT',
    lang_selector: 'Язык',
    nav_ecosystem: 'Экосистема',
    nav_roi: 'Калькулятор ROI',
    nav_partners: 'Партнеры',
    nav_booking: 'Демо-запись',
    nav_faq: 'FAQ',

    // Hero Section
    hero_badge: 'DUAL-CORE SHOWCASE • B2B + B2C ИНТЕГРАЦИЯ',
    hero_title_1: 'Экосистема автоматизации',
    hero_title_gradient: 'фитнеса и спорта',
    hero_subtitle: 'Передовая платформа для управления фитнес-клубами и бассейнами: Объедините B2B CRM-панель и мобильное приложение B2C. Освободите рецепцию от рутины с помощью автоматизированных 24/7 IoT-турникетов, обеспечьте 100% соблюдение трудового законодательства с помощью учета рабочего времени (Приказ №01-15/н) и увеличьте продажи через онлайн-маркетплейс абонементов и тренировок.',
    cta_b2b: 'Запросить B2B демо',
    cta_b2c: 'Мобильное приложение',

    // Hero Stats
    stat_admin_title: '-30% времени',
    stat_admin_desc: 'На административную работу',
    stat_access_title: '24/7 Автоматизация',
    stat_access_desc: 'IoT контроль турникетов',
    stat_bookings_title: '0% упущенных броней',
    stat_bookings_desc: 'С автоматическими ИИ-кампаниями',

    // Dashboard Preview (B2B)
    db_title: 'Панель управления ARTRON',
    db_status: 'IoT Контроллер онлайн',
    db_kpi_members: 'Активные клиенты',
    db_kpi_entries: 'Входы за день',
    db_kpi_winback: 'Коэффициент возврата',
    db_logs_title: 'Лог турникета в реальном времени',
    db_log_in: 'Вошел',
    db_log_out: 'Вышел',
    db_user: 'Пользователь',
    db_employee_time: 'Рабочее время (Приказ №01-15/н)',
    db_toggle_live: 'Живая телеметрия',
    db_toggle_screenshot: 'Интерфейс панели',
    db_screenshot_alt: 'Скриншот панели управления',
    db_screenshot_zoom: 'Нажмите на изображение для увеличения',

    // Business Stats Showcase Section
    stats_sec_title: 'Аналитика панели управления: реальные бизнес-метрики',
    stats_sec_subtitle: 'Artron собирает и анализирует тысячи операционных сигналов, помогая повысить финансовую и организационную эффективность зала.',
    stats_card_ltv_title: 'Удержание клиентов (LTV и Win-Back)',
    stats_card_ltv_metric: '+22%',
    stats_card_ltv_sub: 'Вернувшиеся члены клуба',
    stats_card_ltv_feat1: 'Мгновенные Cron-кампании',
    stats_card_ltv_feat2: 'Снижение оттока клиентов',
    stats_card_ltv_feat3: 'Восстановленный ежемес. доход',
    stats_card_iot_title: 'Автоматизация доступа IoT',
    stats_card_iot_metric: '-45ч',
    stats_card_iot_sub: 'Сэкономлено времени в неделю',
    stats_card_iot_feat1: '100% автономные турникеты',
    stats_card_iot_feat2: 'Нулевая нагрузка на рецепцию',
    stats_card_iot_feat3: 'Контроль Anti-Passback',
    stats_card_labor_title: 'Трудовой комплаенс (Приказ №01-15/н)',
    stats_card_labor_metric: '100%',
    stats_card_labor_sub: 'Безопасность при проверках',
    stats_card_labor_feat1: 'Автоматические табели входов/выходов',
    stats_card_labor_feat2: 'Соответствие требованиям инспекции',
    stats_card_labor_feat3: 'Избежание штрафных санкций',
    stats_card_trainers_title: 'Продажи тренеров',
    stats_card_trainers_metric: '+35%',
    stats_card_trainers_sub: 'Рост продаж пакетов услуг',
    stats_card_trainers_feat1: 'Онлайн-маркетплейс в приложении',
    stats_card_trainers_feat2: 'Нулевой конфликт расписаний',
    stats_card_trainers_feat3: 'Автоматический учет комиссий',

    // Mobile Preview (B2C)
    mobile_title: 'Мобильное приложение ARTRON',
    mobile_welcome: 'Привет, атлет!',
    mobile_qr_pass: 'Динамический QR-код',
    mobile_qr_desc: 'Сканируйте для входа через турникет',
    mobile_sub_status: 'Мой абонемент',
    mobile_sub_active: 'Активен • осталось 14 дней',
    mobile_progress: 'Моя активность',
    mobile_workouts: 'Пройдено тренировок',
    mobile_nfc_desc: 'NFC доступ включен',

    // Cookie Banner
    cookie_title: 'Управление файлами Cookie и согласием',
    cookie_desc: 'ООО «Артрон» (ИНН 412799431, Кутаиси, ул. Никеа, N 46A, кв. 17, info@artron.ge) использует файлы cookie для оптимизации работы сайта, аналитики и маркетинга в соответствии с Google Consent Mode v2.',
    cookie_accept_all: 'Принять все',
    cookie_decline_all: 'Отклонить все',
    cookie_settings: 'Настройки',
    cookie_save: 'Сохранить выбор',
    cookie_necessary_title: 'Необходимые',
    cookie_necessary_desc: 'Обязательны для работы сайта и безопасности (язык, сессия). Не требуют согласия.',
    cookie_analytics_title: 'Аналитика',
    cookie_analytics_desc: 'Позволяет нам измерять трафик сайта и поведение пользователей (Google Analytics).',
    cookie_marketing_title: 'Маркетинг',
    cookie_marketing_desc: 'Используется для показа персонализированной рекламы и отслеживания Google Ads.',
    cookie_policy_link: 'Политика конфиденциальности',

    // Services Section
    services_section_title: 'Экосистема сервисов',
    services_section_subtitle: 'Двойная сила Artron — единая платформа для бизнеса и спортсменов',
    services_tab_b2b: 'B2B Бизнес-инфраструктура',
    services_tab_b2c: 'B2C Мобильное приложение',
    service_iot_title: 'IoT Интеграция оборудования',
    service_iot_desc: 'Прямое TCP/Socket подключение к турникетам, биометрическим и NFC сканерам. Круглосуточный автоматический доступ без персонала.',
    service_worktime_title: 'Учет рабочего времени (Приказ №01-15/н)',
    service_worktime_desc: 'Полное соответствие требованиям Трудовой инспекции Грузии. Биометрический вход/выход, авто-табели и экспорт данных.',
    service_worktime_short: 'Рабочее время (Приказ №01-15/н)',
    service_federation_title: 'Управление федерациями',
    service_federation_desc: 'Централизованное управление лицензированием, реестрами спортсменов и турнирами. Связующий модуль для клубов и атлетов.',
    service_marketplace_title: 'Маркетплейс абонементов',
    service_marketplace_desc: 'Онлайн-продажи абонементов, персональных тренировок и товаров. Встроенный возврат средств по закону в течение 14 дней.',
    service_passbook_title: 'Мобильный пропуск и QR Pass',
    service_passbook_desc: 'Безопасный доступ по динамическому QR-коду или NFC. Исключает утерю карт и передачу пропуска третьим лицам.',
    service_metrics_title: 'Спортивные метрики и прогресс',
    service_metrics_desc: 'Календарь визитов, история тренировок, показатели активности и рейтинги тренеров в реальном времени.',

    // ROI Calculator
    roi_title: 'ROI Калькулятор окупаемости',
    roi_subtitle: 'Рассчитайте прямую финансовую и операционную выгоду от внедрения Artron',
    roi_members_label: 'Активные клиенты',
    roi_staff_label: 'Сотрудники и тренеры',
    roi_time_saved_title: 'Сэкономлено времени',
    roi_time_saved_desc: 'часов в месяц на регистрации и учете времени',
    roi_revenue_title: 'Дополнительный доход',
    roi_revenue_desc: 'годовой прирост за счет онлайн-продаж и удержания',
    roi_overhead_title: 'Экономия расходов',
    roi_overhead_desc: 'снижение операционных затрат в месяц',
    roi_cta: 'Заказать бесплатную демо-презентацию',

    // FAQ Section
    faq_title: 'Часто задаваемые вопросы',
    faq_subtitle: 'Найдите ответы о платформе Artron, оборудовании IoT и юридических аспектах',
    faq_tab_all: 'Все вопросы',
    faq_tab_b2b: 'Для B2B бизнеса',
    faq_tab_b2c: 'Для B2C спортсменов',
    faq_q1: 'Сколько времени занимает установка IoT-турникета?',
    faq_a1: 'Физическая установка и настройка сети обычно занимаются от 1 до 3 рабочих дней. Наша команда предоставляет полную техническую поддержку и интеграцию с платформой ARTRON.',
    faq_q2: 'Как обеспечивается безопасность данных и изоляция арендаторов (Multi-Tenancy)?',
    faq_a2: 'Данные каждого клиента строго изолированы на логическом уровне и уровне базы данных. Чувствительные персональные данные шифруются с использованием алгоритма AES-256-GCM.',
    faq_q3: 'Соответствует ли учет рабочего времени законодательству Грузии (Приказ №01-15/н)?',
    faq_a3: 'Да, модуль учета рабочего времени Artron полностью соответствует требованиям Приказа №01-15/н Министра труда, здравоохранения и социальной защиты Грузии. Система автоматически генерирует электронные табели для инспекции труда.',
    faq_q4: 'Что происходит при расторжении договора? Как экспортируются данные (30-дневное правило)?',
    faq_a4: 'При расторжении подписки операционные данные хранятся в течение 30 дней для полного экспорта. По истечении этого срока данные безвозвратно удаляются, за исключением финансовых транзакций, которые хранятся 3 года в соответствии с Налоговым кодексом Грузии.',
    faq_q5: 'Распространяется ли 14-дневное окно возврата средств на абонементы, купленные через мобильное приложение?',
    faq_a5: 'Да, в соответствии с Законом Грузии «О защите прав потребителей», на абонементы, купленные через мобильное приложение, действует 14-дневное окно возврата, если использование услуг еще не началось.',
    faq_q6: 'Насколько безопасен мобильный QR-пропуск? Можно ли его передать другому человеку?',
    faq_a6: 'Мобильный QR-пропуск ARTRON является динамическим и обновляется каждые 15 секунд. Использование скриншотов заблокировано, что полностью исключает несанкционированную передачу пропуска третьим лицам.',
    faq_q7: 'Работает ли турникет при отключении интернета (Offline-режим)?',
    faq_a7: 'Да, контроллеры турникетов хранят локальный кэш активных пропусков. Даже в случае отключения интернета авторизованные клиенты и сотрудники смогут войти, а все логи посещений синхронизируются после восстановления связи.',

    // AI Bot Widget
    ai_widget_launcher: 'Задать вопрос ИИ',
    ai_widget_title: 'ИИ-ассистент ARTRON',
    ai_widget_subtitle: 'В сети • Отвечает мгновенно',
    ai_widget_placeholder: 'Введите ваш вопрос...',
    ai_widget_welcome: 'Здравствуйте! Я интеллектуальный помощник Artron. Чем я могу помочь вам сегодня?',
    ai_widget_quick_1: 'Установка турникета',
    ai_widget_quick_2: 'Рабочее время (№01-15/н)',
    ai_widget_quick_3: 'Возврат средств',
    ai_widget_typing: 'ИИ пишет ответ...',
    ai_widget_send: 'Отправить',

    // Footer
    footer_desc: 'ООО «Артрон» предлагает современную экосистему B2B SaaS и мобильное приложение B2C для управления спортивными комплексами и фитнес-клубами.',
    footer_col_legal: 'Юридическая информация',
    footer_col_contact: 'Контакты',
    footer_company_id: 'ООО «Артрон» (ИНН 412799431)',
    footer_address: 'Грузия, Кутаиси, ул. Никеа, N 46A, кв. 17',
    footer_cookie_prefs: 'Настройки Cookie',
    footer_all_rights: 'Все права защищены.',

    // Legal Disclosures Header / Helpers
    legal_last_updated: 'Последнее обновление: 10 августа 2026 г.',
    legal_back_to_home: '← На главную страницу',
    legal_toc_title: 'Содержание',
    legal_official_identifier: 'Официальные реквизиты: ООО «Артрон» (ИНН: 412799431), Грузия, Кутаиси, ул. Никеа, N 46А, кв. 17 | info@artron.ge',

    // Privacy Policy
    privacy_title: 'Политика конфиденциальности',
    privacy_subtitle: 'Защита данных, шифрование и биометрическая безопасность в экосистеме Artron',
    privacy_sec_operator_title: '1. Официальный оператор и контакты',
    privacy_sec_operator_body: 'Оператором обработки персональных данных является ООО «Артрон» (идентификационный код: 412799431), юридический адрес: Грузия, Кутаиси, ул. Никеа, N 46А, кв. 17. Контактный адрес: info@artron.ge. Наша команда по информационной безопасности постоянно проверяет системы на соответствие высшим стандартам конфиденциальности.',
    privacy_sec_roles_title: '2. Роли обработчика и контроллера данных',
    privacy_sec_roles_body: 'ООО «Артрон» действует как Технический обработчик данных (Data Processor) для информации, загружаемой B2B-клиентами (спортклубами, работодателями, федерациями), включая учет рабочего времени сотрудников согласно Приказу №01-15/н, медицинские коды и реестры спортсменов. ООО «Артрон» действует как Контроллер данных (Data Controller) при обработке учетных записей мобильного приложения, логов авторизации и системных журналов.',
    privacy_sec_security_title: '3. Безопасность данных и стандарты шифрования',
    privacy_sec_security_body: 'Все чувствительные идентификационные поля (например, личный номер / National ID) защищены шифрованием на уровне столбцов (Column-Level Encryption) с алгоритмом AES-256-GCM при хранении. Пароли хэшируются с использованием безопасных функций (bcrypt/argon2). Финансовые транзакции полностью изолированы в соответствии со стандартами PCI-DSS; платежные карты не хранятся на наших серверах.',
    privacy_sec_biometrics_title: '4. Биометрические и специальные категории данных',
    privacy_sec_biometrics_body: 'Фотографии профиля, используемые для верификации на турникетах, классифицируются как Биометрические данные. Медицинские справки и коды отпусков по болезни представляют собой специальные категории данных о здоровье. Их обработка строго ограничена ролевым доступом (RBAC) и требует явного предварительного согласия пользователя.',
    privacy_sec_erasure_title: '5. Сроки хранения и удаления данных',
    privacy_sec_erasure_body: 'Удаление аккаунта по запросу из мобильного приложения или по электронной почте завершается в течение 15 календарных дней. Специальные категории данных и биометрические фотографии удаляются в течение 5 календарных дней. В соответствии с Налоговым кодексом Грузии, финансовые записи и история покупок архивируются на 3 года перед окончательным уничтожением.',
    privacy_sec_rights_title: '6. Права субъекта данных',
    privacy_sec_rights_body: 'Согласно Закону Грузии «О защите персональных данных» и регламенту GDPR, вы имеете право на доступ к своим данным, их исправление, удаление или ограничение их обработки. По любым вопросам обращайтесь на info@artron.ge.',

    // Terms of Use
    terms_title: 'Условия использования',
    terms_subtitle: 'Правила пользования веб-сайтом и SaaS-платформой Artron',
    terms_sec_license_title: '1. Лицензия на подписку SaaS',
    terms_sec_license_body: 'ООО «Артрон» предоставляет пользователям ограниченную, неисключительную, непередаваемую и отзывную лицензию на доступ к платформе по модели подписки (SaaS Subscription). Исходный код платформы, дизайн и структуры баз данных остаются исключительной интеллектуальной собственностью ООО «Артрон». Подписка предоставляет только доступ к системе и не передает авторские права.',
    terms_sec_security_title: '2. Ограничения безопасности',
    terms_sec_security_body: 'Пользователям строго запрещено реконструировать (reverse-engineer) платформу, совершать попытки внедрения SQL/NoSQL инъекций или отправлять вредоносные скрипты. Все формы проходят валидацию. Любые нарушения приведут к немедленной блокировке доступа.',
    terms_sec_refunds_title: '3. Оплата и политика возврата (B2B и B2C)',
    terms_sec_refunds_body: 'В соответствии с Законом Грузии «О защите прав потребителей», для подписок в мобильном приложении действует установленное законом 14-дневное окно для безусловного возврата средств, если использование услуг еще не началось. Для B2B-клиентов спортивный комплекс является официальным получателем средств за абонементы и обязан самостоятельно осуществлять возврат в соответствии с законом.',
    terms_sec_offboarding_title: '4. Прекращение обслуживания и удаление данных арендатора',
    terms_sec_offboarding_body: 'При расторжении B2B-контракта активные операционные данные (расписания, списки клиентов) хранятся в течение 30 календарных дней для экспорта, после чего удаляются. Финансовые логи архивируются на 3 года для налоговой отчетности.',
    terms_sec_liability_title: '5. Ограничение ответственности',
    terms_sec_liability_body: 'ООО «Артрон» не несет ответственности за договорные и физические отношения между спортивными клубами и атлетами, включая качество тренировок. Платформа предоставляется по принципу «как есть» (as is).',

    // Cookie Policy
    cookie_policy_title: 'Политика использования файлов Cookie',
    cookie_policy_subtitle: 'Категории файлов cookie, управление согласием и стандарты безопасности',
    cookie_policy_sec_desc_title: '1. Что такое файлы Cookie?',
    cookie_policy_sec_desc_body: 'Файлы cookie — это небольшие текстовые файлы, сохраняемые на вашем устройстве при посещении нашего сайта. Они помогают нам запомнить выбранный язык, идентификатор сессии и настройки безопасности.',
    cookie_policy_sec_categories_title: '2. Категории файлов Cookie',
    cookie_policy_sec_categories_body: 'Мы используем: 1. Необходимые файлы cookie (например, artron_cookie_consent, язык, сессия), обязательные для работы сайта; 2. Аналитические файлы cookie (Google Analytics) для измерения трафика; 3. Маркетинговые файлы cookie (Google Ads) для персонализации рекламы.',
    cookie_policy_sec_consent_title: '3. Google Consent Mode v2',
    cookie_policy_sec_consent_body: 'На сайте реализован Google Consent Mode v2. По умолчанию аналитические и маркетинговые файлы cookie отключены (\'denied\'). Они активируются только после явного согласия пользователя в панели настроек. Все IP-адреса передаются в анонимизированном режиме.',
    cookie_policy_sec_apple_title: '4. Соответствие Apple ATT в WebView',
    cookie_policy_sec_apple_body: 'Для мобильных WebView и приложений под iOS, Artron полностью следует правилам Apple App Tracking Transparency (ATT). Мы не отслеживаем поведение пользователей в приложениях и на сайтах третьих сторон без предварительного согласия на уровне устройства.',
    cookie_policy_sec_manage_body: 'Вы можете изменить или отозвать свои предпочтения в любое время, нажав на ссылку «Настройки Cookie» в футере сайта, которая снова откроет панель управления согласием.',
    del_acc_title: 'Удаление аккаунта',
    del_acc_subtitle: 'Процедура деактивации аккаунта и удаления данных',
    del_acc_sec_overview_title: '1. Обзор и соответствие требованиям',
    del_acc_sec_overview_body: 'В соответствии с обязательными правилами Apple App Store и Google Play Store по удалению аккаунтов, а также Законом Грузии «О защите персональных данных», пользователи ARTRON имеют право потребовать полного удаления своего аккаунта и связанных с ним данных. Эта страница описывает наш двухфазный протокол удаления и позволяет отправить запрос напрямую.',
    del_acc_sec_protocol_title: '2. Двухфазный протокол удаления данных',
    del_acc_sec_protocol_body: 'Процедура удаления состоит из следующих этапов: 1. Немедленная деактивация: После подтверждения ваш аккаунт деактивируется, доступ к системе приостанавливается; 2. 15-дневный льготный период: Вы можете восстановить аккаунт в течение 15 календарных дней, связавшись со службой поддержки; 3. 3-летнее обязательное архивирование: В соответствии с Налоговым кодексом Грузии и стандартами Инспекции труда (включая Приказ №01-15/н), финансовые операции и логи рабочего времени архивируются на 3 года перед окончательным уничтожением.',
    del_acc_sec_form_title: '3. Форма запроса на удаление аккаунта',
    del_acc_sec_form_body: 'Заполните форму ниже для начала процесса удаления аккаунта. Укажите зарегистрированный адрес электронной почты или номер телефона и причину удаления.',
    del_acc_label_identity: 'Зарегистрированный email или номер телефона',
    del_acc_placeholder_identity: 'user@artron.ge или +995 599 123 456',
    del_acc_label_reason: 'Причина удаления аккаунта',
    del_acc_placeholder_reason: 'Пожалуйста, кратко опишите причину (необязательно)',
    del_acc_check_grace: 'Я подтверждаю, что мне известен 15-дневный льготный период для восстановления аккаунта.',
    del_acc_check_archival: 'Я подтверждаю, что понимаю условия 3-летнего архивирования финансовых и рабочих данных.',
    del_acc_btn_submit: 'Запросить удаление аккаунта',
    del_acc_btn_submitting: 'Отправка запроса...',
    del_acc_success_title: 'Запрос успешно отправлен',
    del_acc_success_desc: 'Ваш запрос на удаление аккаунта зарегистрирован. Вы получите письмо или SMS-сообщение с инструкциями для подтверждения деактивации.',
    del_acc_error_identity: 'Пожалуйста, введите корректный email или номер телефона',
    del_acc_error_checkboxes: 'Пожалуйста, примите оба условия для продолжения.',

    // B2B SaaS Agreement
    b2b_agreement_title: 'B2B SaaS Генеральное соглашение об услугах (MSA)',
    b2b_agreement_subtitle: 'Основные условия соглашения об обслуживании и лицензировании между ООО «Артрон» и спортивными центрами/федерациями',
    b2b_sec_scope_title: '1. Область действия услуг и функционал',
    b2b_sec_scope_body: 'Данное соглашение регулирует доступ к B2B SaaS платформе Artron, включая: 1) Панель управления администратора (SaaS Web Panel) для управления спортивными объектами, сотрудниками и тренерами; 2) IoT Turnstile Relay API для интеграции с оборудованием и автоматического контроля доступа; 3) Интегрированное мобильное приложение для клиентов (Athlete Mobile Integration), поддерживающее динамические QR-пропуска, онлайн-оплату и календари занятий.',
    b2b_sec_sla_title: '2. Соглашение об уровне услуг (SLA) и гарантия доступности',
    b2b_sec_sla_body: 'ООО «Артрон» обязуется поддерживать 99.9% ежемесячной доступности серверов SaaS и API (Uptime Guarantee). О плановых технических работах клиенты уведомляются не менее чем за 24 часа. Форс-мажорные обстоятельства, сбои интернет-провайдеров или проблемы с локальной сетью клиента не включаются в расчет гарантии доступности.',
    b2b_sec_pricing_title: '3. Тарифные планы и условия оплаты подписки',
    b2b_sec_pricing_body: 'Стоимость доступа определяется выбранным тарифным планом (Starter, Pro, Enterprise). Оплата взимается ежемесячно или ежегодно по предоплате. Срок оплаты составляет 5 календарных дней с начала расчетного периода. В случае просрочки платежа ООО «Артрон» оставляет за собой право приостановить доступ к панели управления и API синхронизации турникетов.',
    b2b_sec_labor_title: '4. Соответствие требованиям Инспекции труда Грузии (Приказ №01-15/н)',
    b2b_sec_labor_body: 'Интегрированный в Artron модуль учета рабочего времени полностью соответствует требованиям Приказа №01-15/н Министра труда, здравоохранения и социальной защиты Грузии. Система обеспечивает автоматическую фиксацию входа/выхода сотрудников через IoT-устройства, рассчитывает рабочее время и генерирует электронные табели, обязательные для инспекции труда.',
    b2b_sec_dpa_title: '5. Соглашение об обработке данных (DPA) и стандарты шифрования',
    b2b_sec_dpa_body: 'В рамках настоящего соглашения ООО «Артрон» действует исключительно как Обработчик данных (Data Processor) от имени Клиента (Data Controller). Стороны соглашаются, что конфиденциальная информация, такая как личные номера спортсменов (National ID), шифруется при хранении с использованием алгоритма AES-256-GCM на уровне столбцов. Биометрические фото и медицинские данные обрабатываются исключительно в рамках ролевого контроля доступа (RBAC).',
    b2b_sec_termination_title: '6. Расторжение, 30-дневный экспорт и 3-летний архив',
    b2b_sec_termination_body: 'В случае расторжения договора клиенту предоставляется 30 календарных дней для полного экспорта операционных данных (истории посещений, списков клиентов). По истечении этого срока живые данные удаляются. В соответствии с Налоговым кодексом Грузии, логи финансовых транзакций и история платежей архивируются на 3 года для целей налогового аудита.',

    // About Us Page
    about_title: 'О нас',
    about_subtitle: 'Лидер автоматизации в индустрии фитнеса и спорта',
    about_mission_title: 'Миссия компании',
    about_mission_body: 'Цифровая трансформация грузинских фитнес-центров и спортивных федераций, оптимизация операционных расходов и улучшение клиентского опыта с помощью современных технологий.',
    about_who_title: 'Кто мы такие',
    about_who_body: 'Мы — базирующиеся в Грузии эксперты в области аппаратных реле IoT (интернета вещей) и облачной архитектуры SaaS, создающие надежные и масштабируемые системы для спортивной индустрии.',
    about_compliance_title: 'Локальное соответствие',
    about_compliance_body: 'Полная интеграция с юридическими требованиями Грузии, включая Приказ Инспекции труда №01-15/н (учет рабочего времени) и локальную круглосуточную техподдержку.',
    about_identity_title: 'Официальные реквизиты',
    about_identity_body: 'ООО «Артрон» (ИНН: 412799431), юридический адрес: Грузия, Кутаиси, ул. Никеа, N 46A, кв. 17. Официальный канал связи: info@artron.ge.',
    about_feat_support_title: 'Локальная поддержка 24/7',
    about_feat_support_desc: 'Гарантированная круглосуточная поддержка на грузинском языке, быстрое реагирование и помощь на месте.',
    about_feat_iot_title: 'Надежность IoT оборудования',
    about_feat_iot_desc: 'Собственные релейные контроллеры и автономная работа турникетов даже при отключении интернета.',
    about_feat_privacy_title: 'Конфиденциальность и AES-256-GCM',
    about_feat_privacy_desc: 'Шифрование конфиденциальных данных на уровне столбцов и строгий ролевой контроль доступа (RBAC).',
    about_feat_legal_title: 'Юридическое соответствие',
    about_feat_legal_desc: 'Соответствие Приказу Инспекции труда №01-15/н и Закону о защите прав потребителей Грузии.',
    about_cta_title: 'Готовы автоматизировать ваш спортивный объект?',
    about_cta_desc: 'Испытайте двойную силу платформы Artron — B2B панель управления и B2C мобильное приложение.',
    about_cta_button: 'Запросить демо-версию',

    // Dashboard Features Section
    dashboardFeatures_title: 'Панель управления B2B',
    dashboardFeatures_subtitle: 'Основной командный центр для фитнес-предприятий и спортивных федераций.',
    dashboardFeatures_feat1_title: 'Управление IoT-турникетами и дверьми в реальном времени',
    dashboardFeatures_feat1_desc: 'Аварийное разблокирование, живая телеметрия и релейная маршрутизация TCP/UDP для безопасного доступа.',
    dashboardFeatures_feat2_title: 'Управление базой членов и спортсменов',
    dashboardFeatures_feat2_desc: 'Отслеживание статусов подписок, индивидуальные тарифные планы и мгновенная генерация динамических QR-пропусков.',
    dashboardFeatures_feat3_title: 'Табели учета рабочего времени (Приказ №01-15/н)',
    dashboardFeatures_feat3_desc: 'Автоматический учет рабочего времени персонала, защищенные журналы аудита и полное соответствие стандартам.',
    dashboardFeatures_feat4_title: 'Финансовая аналитика и Multi-Tenancy',
    dashboardFeatures_feat4_desc: 'Отслеживание доходов, динамические отчеты и управление филиалами под одной учетной записью (Single Sign-On).',

    // Mockup UI translations
    dashboardFeatures_panel_title: 'Панель управления (B2B)',
    dashboardFeatures_panel_status: 'Система активна',
    dashboardFeatures_gate_name: 'Главный входной турникет',
    dashboardFeatures_emergency_btn: 'Аварийная разблокировка',
    dashboardFeatures_remote_unlock: 'Дистанционная разблокировка',
    dashboardFeatures_unlocked_pulse: 'Открыто на 5 сек',
    dashboardFeatures_locked_state: 'Заблокировано',
    dashboardFeatures_unlocked_state: 'Разблокировано',
    dashboardFeatures_status: 'Статус',
    dashboardFeatures_relay: 'UDP-маршрутизация реле',
    dashboardFeatures_relay_on: 'Активно',
    dashboardFeatures_relay_off: 'Отключено',
    dashboardFeatures_logs_title: 'Живые логи телеметрии',
    dashboardFeatures_db_name: 'Имя и фамилия',
    dashboardFeatures_db_status: 'Абонемент',
    dashboardFeatures_db_status_active: 'Активен',
    dashboardFeatures_db_tier: 'Категория',
    dashboardFeatures_db_tier_vip: 'VIP участник',
    dashboardFeatures_db_id: 'Личный номер',
    dashboardFeatures_db_encrypted: 'Зашифровано (AES-256)',
    dashboardFeatures_db_qr: 'Динамический QR',
    dashboardFeatures_db_qr_gen: 'Создать QR',
    dashboardFeatures_labor_title: 'Учет рабочего времени (Приказ №01-15/н)',
    dashboardFeatures_labor_audits: 'Журнал защищенного аудита',
    dashboardFeatures_labor_audits_show: 'Показать крипто-логи',
    dashboardFeatures_fin_revenue: 'Еженедельный доход',
    dashboardFeatures_fin_branches: 'Филиалы',
    dashboardFeatures_fin_branch_tb: 'Тбилиси Ваке',
    dashboardFeatures_fin_branch_bt: 'Батуми Бульвар',
    dashboardFeatures_fin_branch_kt: 'Кутаиси Никея',
    partner_title: 'Интегрированные партнеры',
    partner_subtitle: 'Экосистема Artron синхронизирована с ведущими финтех-платформами и системами контроля доступа',
    partner_fintech: 'Финтех и Биллинг',
    partner_access: 'Контроль доступа и Оборудование',
    partner_iot: 'IoT и Реле',
    booking_title: 'Забронировать демо-встречу',
    booking_subtitle: 'Проконсультируйтесь с нашими инженерами и выберите оптимальный план автоматизации',
    booking_map_hq: 'Центральный штаб-квартира ARTRON',
    booking_map_coords: 'Адрес: ул. Никеа, N 46А, Кутаиси • 42.2496° N, 42.7015° E',
    booking_map_status: 'Статус: Активен (Онлайн)',
    booking_map_desc: 'Операционный центр Artron и производственная лаборатория IoT-оборудования.',
    booking_fallback_title: 'Запросить презентацию',
    booking_fallback_name: 'Имя и фамилия',
    booking_fallback_email: 'Эл. почта',
    booking_fallback_phone: 'Номер телефона',
    booking_fallback_type: 'Тип объекта',
    booking_fallback_submit: 'Забронировать презентацию',
    booking_fallback_success: 'Запрос успешно зарегистрирован! Наша команда свяжется с вами в ближайшее время.',
    cta_title: 'Сделайте ваш спортзал умным сегодня',
    cta_subtitle: 'Присоединяйтесь к новой эре автоматизации фитнес-бизнеса. Экономьте время, снижайте расходы и управляйте всем централизованно.',
    cta_btn_book: 'Забронировать демо (Cal.com)',
    cta_btn_register: 'Зарегистрировать филиал',

    // Core Analytical Modules Copy
    analytics_kpi_title: '📊 Панель KPI (Контроль здоровья бизнеса)',
    analytics_kpi_subtitle: 'Финансовые и операционные метрики в реальном времени',
    analytics_kpi_bullet1: '<strong>Мониторинг MRR и LTV</strong>: Отслеживайте ежемесячный регулярный доход и пожизненную ценность клиента.',
    analytics_kpi_bullet2: '<strong>Аналитика CAC</strong>: Оценивайте реальную стоимость привлечения клиентов по маркетинговым каналам.',
    analytics_kpi_bullet3: '<strong>Операционные метрики</strong>: Общее число активных членов, коэффициент чистого прироста и динамика посещений.',
    analytics_market_title: '🌐 Рыночная и поведенческая аналитика',
    analytics_market_subtitle: 'Анализ спроса клиентов и загруженности зала',
    analytics_market_bullet1: '<strong>Загруженность и тепловые карты</strong>: Карты посещаемости для выявления непиковых часов и планирования скидок.',
    analytics_market_bullet2: '<strong>Демографическая сегментация</strong>: Распределение клиентов по возрасту, полу и геолокации.',
    analytics_market_bullet3: '<strong>Популярность тарифов</strong>: Рейтинг самых продаваемых абонементов и дополнительных услуг (фитнес-бар, персональный тренер).',
    analytics_churn_title: '⚠️ Прогнозирование оттока с ИИ (Предотвращение ухода)',
    analytics_churn_subtitle: 'Модели машинного обучения для предсказания ухода клиентов',
    analytics_churn_bullet1: '<strong>Оценка риска оттока (0-100%)</strong>: Индивидуальный расчет вероятности ухода каждого клиента.',
    analytics_churn_bullet2: '<strong>Выявление аномалий поведения</strong>: Мгновенная фиксация снижения частоты посещений (Drop-in-Frequency).',
    analytics_churn_bullet3: '<strong>Автотриггеры ИИ</strong>: Автоматическая отправка мотивирующих предложений и SMS до того, как клиент уйдет.',
    analytics_winback_title: '🔄 Аналитика возврата (Реактивация ушедших)',
    analytics_winback_subtitle: 'Возвращение пассивных и потерянных клиентов',
    analytics_winback_bullet1: '<strong>Сегментация неактивности</strong>: Недавно ушедшие (14-30 дней), средний риск (30-60 дней) и потерянные (90+ дней).',
    analytics_winback_bullet2: '<strong>ROI кампаний и A/B тестирование</strong>: Анализ эффективности SMS/Email рассылок (-15% скидка против бесплатной персональной тренировки).',
    analytics_winback_bullet3: '<strong>Стоимость возврата против CAC</strong>: Сравнение расходов на возвращение старого клиента с затратами на привлечение нового.',
    
    // Additional ROI Labels
    roi_price_label: 'Средняя цена абонемента',
  },
};

interface LanguageContextProps {
  locale: Locale;
  setLocale: (locale: Locale) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextProps | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [locale, setLocaleState] = useState<Locale>('ka');

  useEffect(() => {
    // Initial detection on client side
    const saved = localStorage.getItem('artron_lang');
    if (saved === 'ka' || saved === 'en' || saved === 'ru') {
      setLocaleState(saved);
    } else {
      const browserLang = navigator.language.substring(0, 2);
      if (browserLang === 'ru') {
        setLocaleState('ru');
      } else if (browserLang === 'en') {
        setLocaleState('en');
      } else {
        setLocaleState('ka');
      }
    }
  }, []);

  const setLocale = (newLocale: Locale) => {
    setLocaleState(newLocale);
    localStorage.setItem('artron_lang', newLocale);
  };

  const t = (key: string): string => {
    return translations[locale]?.[key] || translations['en']?.[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ locale, setLocale, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
